import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {strings} from './i18n';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,systemName,buildNames,displayName,latinName,type Atlas,type Concept,type Lang,type Names,type SceneState,type SystemId,type Translation,type View,type InfoDe,infoFor} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[lang,setLang]=useState<Lang>(()=>typeof navigator!=='undefined'&&navigator.language.toLowerCase().startsWith('de')?'de':'en'),[names,setNames]=useState<Names|null>(null),[info,setInfo]=useState<InfoDe|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('LOAD_ERROR');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});fetch('/models/atlas-de.json',{signal:abort.signal}).then(r=>r.ok?r.json():null).then(t=>{if(t)setNames(buildNames(t as Translation));}).catch(()=>{});fetch('/models/info-de.json',{signal:abort.signal}).then(r=>r.ok?r.json():null).then(i=>{if(i)setInfo(i as InfoDe);}).catch(()=>{});return()=>abort.abort();},[]);
 const t=strings(lang);const sysName=(id:SystemId)=>systemName(id,lang);
 const name=(id:string,english:string)=>displayName(id,english,lang,names);
 const conceptLabel=(c:Concept|null)=>c?name(c.id,c.name):'';
 const box=lang==='de'&&chosen?infoFor(info,chosen.id):null;
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);const hit=(c:Concept)=>{const n=names?.get(c.id);return c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)||(!!n&&(n.de.toLowerCase().includes(term)||n.la.toLowerCase().includes(term)));};return atlas.concepts.filter(hit).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query,names]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError} label={name}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {t.eyebrow}</div><h1>Human Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} {t.pieces} <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t.findAria}><Search size={18}/><span>{t.find}</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button lang-toggle" aria-label={t.langToggle} title={t.langTitle} onClick={()=>setLang(l=>l==='en'?'de':'en')}>{lang==='en'?'DE':'EN'}</Button><Button variant="ghost" className="icon-button" aria-label={t.about} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={t.layersAria}>
   <div className="panel-heading"><span>{t.systems}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t.closeSystems}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t.all}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t.skeleton}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t.organs}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`${t.showOnly} ${sysName(s.id)}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{sysName(s.id)}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`${t.show} ${sysName(s.id)}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} {t.visible}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t.hideAll}</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label={t.findAria2}><div className="panel-heading"><span>{t.find}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t.closeSearch}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>conceptLabel(c)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={t.searchPlaceholder} aria-label={t.searchAria} showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t.noMatch}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{conceptLabel(c)}{lang==='de'&&latinName(c.id,names)&&<small className="search-latin">{latinName(c.id,names)}</small>}</span><span className="small-number">{c.elements.length} {c.elements.length===1?t.piece:t.piecesWord}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t.noteQuery:t.noteEmpty}</p></section>}
  <nav className="view-controls glass" aria-label={t.cameraAria}>{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${t.views[i]} ${t.view}`} aria-label={`${t.views[i]} ${t.view}`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?t.pauseRotation:t.rotateBody} title={t.autoRotate} className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label={t.resetAria} title={t.reset} onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(conceptLabel(chosen)||t.selectedStructure):state.explode>.95?t.inventory:state.explode>.05?t.separated:t.adultMale}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t.openLayers}><Layers3 size={20}/><span>{t.systems}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t.explode}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t.assembled}</span><span>{t.everyPiece}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t.assembleReset}><RotateCcw size={18}/><span>{t.reset}</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?t.dragPan:t.dragOrbit} <b>·</b> {t.pinch} <b>·</b> {t.tap} <b className="desktop-only">·</b> <span className="desktop-only">{t.keysHint}</span></span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t.credits} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t.preparing}</strong><span>{progress}% · {t.loading} {atlas?.parts.length.toLocaleString()??'2,234'} {t.piecesWord}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error==='LOAD_ERROR'?t.loadError:error}</p><Button variant="ghost" onClick={()=>location.reload()}>{t.reload}</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?sysName(system.id):t.anatomy}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{conceptLabel(chosen)}</SheetTitle>{chosen&&lang==='de'&&latinName(chosen.id,names)&&<div className="structure-latin">{latinName(chosen.id,names)}</div>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{box?box.description:(chosen&&selected?explanation(chosen.name,selected.system,lang):'')}</SheetDescription>{!box&&chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">{t.contextNote}</span>}{box&&(box.nutrients.length>0||box.diseases.length>0)&&<div className="info-box">{box.nutrients.length>0&&<div><h4>{t.nutrients}</h4><p>{box.nutrients.join(' · ')}</p></div>}{box.supplements.length>0&&<div><h4>{t.supplements}</h4><p>{box.supplements.join(' · ')}</p></div>}{box.diseases.length>0&&<div><h4>{t.diseases}</h4><ul>{box.diseases.map(([d,m])=><li key={d}><strong>{d}</strong><span>{t.meds} {m}</span></li>)}</ul></div>}<p className="info-note">{t.infoNote}</p></div>}<div className="structure-meta"><span>{t.atlasRef}<strong>{chosen?.id}</strong></span><span>{t.selectedPieces}<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{t.included}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{name(p.id,p.name)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{t.andMore(selectedParts.length-50)}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t.viewSource} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t.showSurrounding:t.isolate}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t.clear}</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">{t.aboutEyebrow}</div><SheetTitle className="structure-title">{t.aboutTitle}</SheetTitle><SheetDescription>{t.aboutLead}</SheetDescription><div className="about-copy"><p><strong>{t.aboutMeta}</strong><br/>{t.aboutCounts}</p><p>{t.aboutScope}</p><p>{t.aboutUse}</p><h3>{t.source}</h3><p>{t.sourceLine}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t.license} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t.geometry} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t.publication} <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
