# -*- coding: utf-8 -*-
# Each class: description template ({n} = German name, {loc} = region), nutrients, supplements, diseases [(name, medication examples)]
C = {
 'bone': dict(d='{n} ist ein Knochen{loc}. Knochen geben dem Körper Halt, schützen Organe, dienen Muskeln als Ansatz und speichern Mineralstoffe.',
  nu=['Calcium','Vitamin D','Vitamin K2','Magnesium','Phosphat','Eiweiß'], su=['Vitamin D3 (v. a. im Winter)','Calcium bei geringer Zufuhr','Vitamin K2'],
  di=[('Osteoporose','Bisphosphonate (z. B. Alendronat), Denosumab, Vitamin D + Calcium'),('Fraktur','Ruhigstellung/Operation, Schmerzmittel (Ibuprofen, Paracetamol)'),('Osteomyelitis','Antibiotika (z. B. Flucloxacillin, Clindamycin)'),('Knochenmetastasen','Bisphosphonate (Zoledronat), Strahlentherapie')]),
 'vertebra': dict(d='{n} ist ein Wirbel der Wirbelsäule. Wirbel tragen das Körpergewicht, umschließen das Rückenmark und bilden mit den Bandscheiben die bewegliche Achse des Rumpfes.',
  nu=['Calcium','Vitamin D','Magnesium','Eiweiß','Vitamin K2'], su=['Vitamin D3','Calcium bei Mangel','Magnesium'],
  di=[('Osteoporotische Wirbelfraktur','Bisphosphonate, Denosumab, Teriparatid'),('Spondylarthrose / Facettengelenkarthrose','NSAR (Ibuprofen, Diclofenac), Physiotherapie'),('Morbus Bechterew','NSAR, TNF-Blocker (Adalimumab)'),('Spondylodiszitis','Antibiotika, Ruhigstellung')]),
 'disk': dict(d='{n} ist eine Bandscheibe: ein Faserring mit gallertigem Kern zwischen zwei Wirbelkörpern, der Stöße abfängt und Bewegung ermöglicht.',
  nu=['Wasser','Eiweiß','Vitamin C','Magnesium','Omega-3-Fettsäuren'], su=['Vitamin D3','Omega-3','Kollagenhydrolysat (begrenzte Evidenz)'],
  di=[('Bandscheibenvorfall','NSAR, Muskelrelaxanzien, Physiotherapie, ggf. Operation'),('Bandscheibendegeneration','Bewegung, Schmerzmittel, Rückenschule'),('Ischialgie','NSAR, Pregabalin, Kortikosteroid-Injektion')]),
 'rib': dict(d='{n} gehört zum Brustkorb. Die Rippen schützen Herz und Lunge und bewegen sich beim Atmen.',
  nu=['Calcium','Vitamin D','Eiweiß','Magnesium'], su=['Vitamin D3','Calcium bei Mangel'],
  di=[('Rippenfraktur','Schmerzmittel (Ibuprofen, Metamizol), Atemtherapie'),('Rippenprellung','Kühlung, NSAR'),('Tietze-Syndrom','NSAR, Wärme')]),
 'cartilage': dict(d='{n} ist ein Knorpel{loc}. Knorpel ist druckelastisch, gefäßlos und formt Stützgerüste wie Kehlkopf, Nase und Rippenansätze.',
  nu=['Vitamin C','Eiweiß (Kollagen)','Zink','Mangan','Omega-3-Fettsäuren'], su=['Vitamin C','Kollagenhydrolysat','Glucosamin/Chondroitin (begrenzte Evidenz)'],
  di=[('Perichondritis','Antibiotika (Ciprofloxacin), NSAR'),('Knorpelverletzung','Schonung, NSAR, ggf. Operation'),('Relapsierende Polychondritis','Kortikosteroide, Methotrexat')]),
 'tooth': dict(d='{n} ist ein Zahn des bleibenden Gebisses. Zähne zerkleinern Nahrung; Schmelz, Dentin und Pulpa bilden ihren Aufbau, das Zahnfleisch verankert sie.',
  nu=['Calcium','Phosphat','Fluorid','Vitamin D','Vitamin C','Vitamin K2'], su=['Fluorid (Zahnpasta/Gel)','Vitamin D3','Calcium bei Mangel'],
  di=[('Karies','Fluoridierung, Füllung; Schmerz: Ibuprofen'),('Parodontitis','Professionelle Reinigung, Chlorhexidin, ggf. Amoxicillin + Metronidazol'),('Pulpitis / Zahnabszess','Wurzelbehandlung, Amoxicillin, Ibuprofen'),('Zahnfleischentzündung (Gingivitis)','Mundhygiene, Chlorhexidin-Spülung')]),
 'muscle': dict(d='{n} ist ein Skelettmuskel{loc}. Skelettmuskeln erzeugen Bewegung, stabilisieren Gelenke, stützen die Haltung und erzeugen Wärme.',
  nu=['Eiweiß','Magnesium','Kalium','Vitamin D','Kreatin (aus Fleisch/Fisch)','Omega-3-Fettsäuren','B-Vitamine'], su=['Kreatin-Monohydrat','Vitamin D3','Magnesium','Molkenprotein'],
  di=[('Muskelzerrung / Muskelfaserriss','Kühlung, Schonung, NSAR (Ibuprofen), Physiotherapie'),('Muskelkrampf','Dehnung, Magnesium, Flüssigkeit'),('Myositis','Kortikosteroide (Prednisolon), Methotrexat'),('Sarkopenie','Krafttraining, Eiweiß, Vitamin D'),('Statin-Myopathie','Statin anpassen/wechseln, Coenzym Q10 (Evidenz begrenzt)')]),
 'tendon': dict(d='{n} ist eine Sehne bzw. ein Halteapparat{loc}. Sehnen übertragen die Muskelkraft auf den Knochen.',
  nu=['Eiweiß (Kollagen)','Vitamin C','Zink','Kupfer','Mangan'], su=['Kollagenhydrolysat + Vitamin C','Omega-3'],
  di=[('Tendinopathie','Exzentrisches Training, NSAR, Stoßwellentherapie'),('Sehnenriss','Operation oder Ruhigstellung, Schmerzmittel'),('Tendovaginitis','Ruhigstellung, NSAR, Kortikosteroid-Injektion')]),
 'ligament': dict(d='{n} ist ein Band{loc}. Bänder verbinden Knochen oder Knorpel, führen Gelenke und begrenzen Bewegungen.',
  nu=['Eiweiß (Kollagen)','Vitamin C','Zink','Kupfer'], su=['Kollagenhydrolysat + Vitamin C','Vitamin D3'],
  di=[('Bänderdehnung / Bänderriss','PECH-Regel, NSAR, Bandage, ggf. Operation'),('Chronische Instabilität','Physiotherapie, Orthese'),('Verkalkung / Enthesiopathie','NSAR, Stoßwellentherapie')]),
 'fascia': dict(d='{n} ist eine Faszie bzw. Bindegewebsmembran{loc}. Faszien umhüllen Muskeln, verbinden Strukturen und leiten Kräfte weiter.',
  nu=['Eiweiß (Kollagen)','Vitamin C','Wasser','Magnesium'], su=['Kollagenhydrolysat','Magnesium'],
  di=[('Fasziitis / Myofasziales Schmerzsyndrom','Dehnung, Faszientraining, NSAR'),('Kompartmentsyndrom','Notfall-Operation (Fasziotomie)'),('Fibromatose','Physiotherapie, ggf. Operation')]),
 'joint': dict(d='{n} ist eine Gelenkstruktur{loc}, die Knochen beweglich oder straff miteinander verbindet.',
  nu=['Eiweiß (Kollagen)','Vitamin C','Omega-3-Fettsäuren','Vitamin D','Calcium'], su=['Glucosamin/Chondroitin (begrenzte Evidenz)','Omega-3','Vitamin D3'],
  di=[('Arthrose','NSAR, Physiotherapie, Hyaluronsäure-Injektion, Gelenkersatz'),('Arthritis','NSAR, Kortikosteroide, Methotrexat bei Rheuma'),('Gicht','Colchicin, NSAR, Allopurinol'),('Gelenkinstabilität','Physiotherapie, Orthese')]),
 'artery': dict(d='{n} ist eine Arterie{loc}. Arterien führen sauerstoffreiches Blut vom Herzen in die Gewebe; ihre Wand ist muskulös und elastisch.',
  nu=['Omega-3-Fettsäuren','Ballaststoffe','Kalium','Folat','Nitrat (grünes Gemüse, Rote Bete)','Vitamin K2'], su=['Omega-3 (EPA/DHA)','Vitamin K2','Folsäure bei Mangel'],
  di=[('Arteriosklerose','Statine (Atorvastatin), ASS, Blutdrucksenker'),('Bluthochdruck','ACE-Hemmer (Ramipril), Amlodipin, Diuretika'),('Aneurysma','Blutdrucksenkung, Operation oder Stent'),('Arterienverschluss / Thrombose','Thrombozytenhemmer (Clopidogrel), Antikoagulation (Heparin)'),('Vaskulitis','Kortikosteroide, Immunsuppressiva')]),
 'coronary': dict(d='{n} gehört zu den Herzkranzgefäßen{loc}. Die Koronararterien versorgen den Herzmuskel selbst mit Blut und Sauerstoff.',
  nu=['Omega-3-Fettsäuren','Ballaststoffe','Kalium','Magnesium','Vollkorn und Gemüse'], su=['Omega-3 (EPA/DHA)','Coenzym Q10 (Evidenz begrenzt)','Vitamin D3'],
  di=[('Koronare Herzkrankheit','Statine, ASS, Betablocker (Metoprolol), Nitrate'),('Herzinfarkt','Notfall: ASS, Heparin, Clopidogrel/Ticagrelor, Stent (PCI)'),('Angina pectoris','Nitroglycerin, Betablocker, Ranolazin'),('Koronarspasmus','Kalziumantagonisten (Diltiazem)')]),
 'cerebral_artery': dict(d='{n} ist eine hirnversorgende Arterie{loc}. Sie versorgt Hirngewebe mit Sauerstoff und Glukose; ein Verschluss führt zum Schlaganfall.',
  nu=['Omega-3-Fettsäuren (DHA)','Folat','Vitamin B12','Kalium','Antioxidantien (Beeren, Gemüse)'], su=['Omega-3','B-Vitamine bei Mangel'],
  di=[('Ischämischer Schlaganfall','Alteplase (Lyse), Thrombektomie, danach ASS/Clopidogrel, Statine'),('Hirnaneurysma / Subarachnoidalblutung','Clipping oder Coiling, Nimodipin'),('Zerebrale Arteriosklerose','Statine, Blutdrucksenker, ASS'),('Migräne','Triptane, Betablocker zur Vorbeugung')]),
 'pulmonary_artery': dict(d='{n} gehört zum Lungenkreislauf{loc}. Lungenarterien führen sauerstoffarmes Blut vom rechten Herzen zur Lunge.',
  nu=['Omega-3-Fettsäuren','Kalium','Eisen','Vitamin D'], su=['Omega-3','Eisen bei Mangel'],
  di=[('Lungenembolie','Heparin, DOAK (Rivaroxaban, Apixaban), ggf. Lyse'),('Pulmonale Hypertonie','Sildenafil, Endothelin-Antagonisten (Bosentan), Diuretika'),('Pulmonalklappenstenose','Ballondilatation, Operation')]),
 'aorta': dict(d='{n} ist ein Abschnitt der Hauptschlagader. Die Aorta verteilt das Blut aus der linken Herzkammer in den gesamten Körper.',
  nu=['Omega-3-Fettsäuren','Kalium','Ballaststoffe','Vitamin K2','Magnesium'], su=['Omega-3','Vitamin K2'],
  di=[('Aortenaneurysma','Blutdrucksenkung, Stent (EVAR) oder Operation'),('Aortendissektion','Notfall: Betablocker, Operation'),('Aortenklappenstenose','Klappenersatz (TAVI/OP)'),('Arteriosklerose','Statine, ASS, Blutdrucksenker')]),
 'vein': dict(d='{n} ist eine Vene{loc}. Venen führen das Blut zum Herzen zurück; Klappen verhindern den Rückfluss.',
  nu=['Vitamin C','Flavonoide (Beeren, Zitrusfrüchte)','Ballaststoffe','Wasser','Kalium'], su=['Diosmin/Hesperidin','Rosskastanienextrakt','Vitamin C'],
  di=[('Thrombose','Heparin, DOAK (Apixaban, Rivaroxaban), Kompression'),('Krampfadern (Varizen)','Kompressionsstrümpfe, Verödung, Diosmin'),('Thrombophlebitis','NSAR, Kühlung, ggf. Heparin'),('Chronisch-venöse Insuffizienz','Kompression, Bewegung, Diosmin')]),
 'deep_vein': dict(d='{n} ist eine tiefe Vene{loc}. Die tiefen Venen transportieren den Großteil des Blutes zurück zum Herzen und sind der typische Ort einer Thrombose.',
  nu=['Wasser','Vitamin C','Flavonoide','Kalium'], su=['Diosmin/Hesperidin'],
  di=[('Tiefe Venenthrombose','Heparin, DOAK (Apixaban, Rivaroxaban), Kompression'),('Postthrombotisches Syndrom','Kompression, Bewegung'),('Lungenembolie als Folge','Antikoagulation, ggf. Lyse')]),
 'portal_vein': dict(d='{n} gehört zum Pfortadersystem. Es führt nährstoffreiches Blut aus Darm, Milz und Bauchspeicheldrüse zur Leber.',
  nu=['Ballaststoffe','Omega-3-Fettsäuren','Vitamin B12','Folat'], su=['Omega-3','Vitamin D3'],
  di=[('Pfortaderhochdruck','Propranolol, Ösophagusvarizen-Ligatur'),('Pfortaderthrombose','Antikoagulation (Heparin, DOAK)'),('Leberzirrhose als Ursache','Spironolacton, Lactulose, Alkoholverzicht')]),
 'pulmonary_vein': dict(d='{n} gehört zum Lungenkreislauf{loc}. Die Lungenvenen bringen sauerstoffreiches Blut aus der Lunge in den linken Vorhof.',
  nu=['Kalium','Magnesium','Omega-3-Fettsäuren'], su=['Magnesium','Omega-3'],
  di=[('Vorhofflimmern (Ursprung an den Pulmonalvenen)','Pulmonalvenenisolation (Ablation), Antikoagulation (Apixaban), Betablocker'),('Pulmonalvenenstenose','Ballondilatation, Stent'),('Lungenstauung bei Herzinsuffizienz','Diuretika (Furosemid), ACE-Hemmer')]),
 'cardiac_vein': dict(d='{n} gehört zu den Herzvenen. Sie sammeln das Blut aus dem Herzmuskel und leiten es über den Koronarsinus in den rechten Vorhof.',
  nu=['Kalium','Magnesium','Omega-3-Fettsäuren'], su=['Magnesium','Coenzym Q10 (Evidenz begrenzt)'],
  di=[('Koronare Herzkrankheit','Statine, ASS, Betablocker'),('Herzinsuffizienz','ACE-Hemmer, Betablocker, SGLT2-Hemmer (Dapagliflozin), Diuretika')]),
 'brain': dict(d='{n} ist eine Region des Gehirns{loc}. Hirnregionen verarbeiten Sinneseindrücke, steuern Bewegung, Gefühle, Gedächtnis und lebenswichtige Funktionen.',
  nu=['Omega-3 (DHA)','Vitamin B12','Folat','Cholin','Eisen','Jod','Vitamin D','Antioxidantien'], su=['Omega-3 (DHA/EPA)','Vitamin B12 bei Mangel','Vitamin D3','Kreatin (Evidenz begrenzt)'],
  di=[('Schlaganfall','Alteplase, Thrombektomie, ASS, Statine'),('Demenz (Alzheimer)','Donepezil, Memantin, Lecanemab (früh)'),('Epilepsie','Levetiracetam, Lamotrigin, Valproat'),('Hirntumor','Operation, Strahlentherapie, Temozolomid'),('Depression / Angststörung','SSRI (Sertralin), Psychotherapie')]),
 'basal_ganglia': dict(d='{n} gehört zu den Basalganglien. Diese tief liegenden Kerne steuern Bewegungsabläufe, Motivation und Lernen.',
  nu=['Eisen','Omega-3 (DHA)','Vitamin B6/B12','Folat','Vitamin D'], su=['Omega-3','Vitamin D3','Coenzym Q10 (Evidenz begrenzt)'],
  di=[('Parkinson-Krankheit','Levodopa/Carbidopa, Pramipexol, Rasagilin'),('Chorea Huntington','Tetrabenazin, Antipsychotika'),('Dystonie','Botulinumtoxin, Anticholinergika'),('Zwangsstörung / ADHS (Beteiligung)','SSRI bzw. Methylphenidat')]),
 'cerebellum': dict(d='{n} gehört zum Kleinhirn. Es koordiniert Bewegungen, reguliert Gleichgewicht, Muskeltonus und feinmotorische Abläufe.',
  nu=['Vitamin E','Vitamin B1 (Thiamin)','Vitamin B12','Omega-3','Kupfer'], su=['Vitamin B1','Vitamin E bei Mangel'],
  di=[('Ataxie (erblich, alkoholbedingt)','Physiotherapie, Vitamin B1, Alkoholverzicht'),('Kleinhirninfarkt / -blutung','Akutbehandlung wie Schlaganfall, ggf. Operation'),('Kleinhirntumor (z. B. Medulloblastom)','Operation, Strahlen-, Chemotherapie'),('Multiple Sklerose','Interferone, Ocrelizumab, Natalizumab')]),
 'brainstem': dict(d='{n} gehört zum Hirnstamm. Er verbindet Großhirn und Rückenmark und steuert Atmung, Herzschlag, Blutdruck, Schlucken und Bewusstsein.',
  nu=['Vitamin B1','Vitamin B12','Omega-3','Eisen'], su=['B-Vitamine bei Mangel'],
  di=[('Hirnstamminfarkt','Lyse (Alteplase), Thrombektomie, ASS'),('Wernicke-Enzephalopathie','Hochdosiertes Thiamin (Vitamin B1)'),('Multiple Sklerose','Immuntherapie (Ocrelizumab, Fingolimod)'),('Hirnstammtumor','Strahlentherapie, Operation')]),
 'diencephalon': dict(d='{n} gehört zum Zwischenhirn. Thalamus und Hypothalamus filtern Sinnesreize, regulieren Schlaf, Hunger, Temperatur und Hormone.',
  nu=['Jod','Omega-3','Vitamin B12','Tryptophan','Magnesium'], su=['Omega-3','Magnesium','Melatonin bei Schlafstörung'],
  di=[('Thalamusschmerz nach Schlaganfall','Pregabalin, Amitriptylin'),('Hypothalamische Störungen (Hormonmangel)','Hormonersatz (z. B. Desmopressin, Levothyroxin)'),('Schlafstörungen','Schlafhygiene, Melatonin, kurzzeitig Z-Substanzen'),('Narkolepsie','Modafinil, Natriumoxybat')]),
 'limbic': dict(d='{n} gehört zum limbischen System. Diese Strukturen verarbeiten Gefühle, Gedächtnisinhalte und Motivation.',
  nu=['Omega-3 (DHA)','Vitamin B12','Folat','Vitamin D','Magnesium'], su=['Omega-3','Vitamin D3','Magnesium'],
  di=[('Alzheimer-Demenz (Hippocampus zuerst betroffen)','Donepezil, Rivastigmin, Memantin'),('Depression / Angststörung','SSRI (Sertralin, Escitalopram), Psychotherapie'),('Temporallappenepilepsie','Levetiracetam, Lamotrigin, ggf. Operation'),('Posttraumatische Belastungsstörung','Traumatherapie, Sertralin')]),
 'ventricle_brain': dict(d='{n} gehört zum Ventrikelsystem des Gehirns. In diesen Hohlräumen wird Hirnwasser (Liquor) gebildet, das Gehirn und Rückenmark polstert.',
  nu=['Wasser','Vitamin B12','Folat'], su=[],
  di=[('Hydrozephalus','Shunt-Operation, Acetazolamid'),('Ventrikelblutung','Intensivmedizin, Drainage'),('Meningitis','Ceftriaxon, Ampicillin, Dexamethason'),('Idiopathische intrakranielle Hypertension','Acetazolamid, Gewichtsreduktion')]),
 'nerve': dict(d='{n} ist ein Nerv{loc}. Nerven leiten Signale zwischen Gehirn, Rückenmark und Körper – für Empfindung, Bewegung und Organsteuerung.',
  nu=['Vitamin B1','Vitamin B6','Vitamin B12','Folat','Omega-3','Magnesium'], su=['Vitamin B12','B-Komplex','Alpha-Liponsäure (bei diabetischer Neuropathie)'],
  di=[('Neuropathie','Pregabalin, Duloxetin, Amitriptylin, Ursache behandeln'),('Neuralgie','Carbamazepin, Gabapentin'),('Nervenkompression','Physiotherapie, Kortikosteroid-Injektion, Operation'),('Nervenentzündung (Neuritis)','Kortikosteroide, Vitamin B')]),
 'optic': dict(d='{n} gehört zur Sehbahn. Sie leitet die Signale der Netzhaut zur Sehrinde im Hinterhauptslappen.',
  nu=['Vitamin A','Lutein/Zeaxanthin','Omega-3 (DHA)','Vitamin B12','Zink'], su=['Lutein/Zeaxanthin','Omega-3','Vitamin B12 bei Mangel'],
  di=[('Optikusneuritis (oft bei MS)','Hochdosis-Methylprednisolon'),('Glaukom (Sehnervenschaden)','Latanoprost, Timolol, Dorzolamid'),('Ischämische Optikusneuropathie','Risikofaktoren behandeln, ASS'),('Hypophysentumor mit Chiasmadruck','Cabergolin, Operation')]),
 'eye': dict(d='{n} ist ein Teil des Auges{loc}. Die Augenstrukturen bündeln Licht, bilden das Bild und schützen den Augapfel.',
  nu=['Vitamin A','Lutein/Zeaxanthin','Omega-3 (DHA)','Zink','Vitamin C','Vitamin E'], su=['Lutein/Zeaxanthin','Omega-3','AREDS2-Formel bei Makuladegeneration'],
  di=[('Bindehaut-/Hornhautentzündung','Antibiotische Augentropfen (Ofloxacin), künstliche Tränen'),('Grauer Star (Katarakt)','Operation mit Kunstlinse'),('Grüner Star (Glaukom)','Latanoprost, Timolol'),('Trockenes Auge','Tränenersatzmittel, Ciclosporin-Tropfen')]),
 'retina': dict(d='{n} ist die lichtempfindliche Netzhaut{loc}. Ihre Sinneszellen wandeln Licht in Nervensignale um.',
  nu=['Lutein/Zeaxanthin','Vitamin A','Omega-3 (DHA)','Zink','Vitamin C/E'], su=['AREDS2 (Lutein, Zeaxanthin, Zink, Vitamin C/E)','Omega-3'],
  di=[('Altersbedingte Makuladegeneration','Anti-VEGF-Injektionen (Ranibizumab, Aflibercept), AREDS2'),('Diabetische Retinopathie','Blutzuckerkontrolle, Anti-VEGF, Laser'),('Netzhautablösung','Notfall-Operation'),('Retinitis pigmentosa','Vitamin A (umstritten), Gentherapie (Voretigen)')]),
 'lacrimal': dict(d='{n} gehört zum Tränenapparat{loc}. Er bildet, verteilt und leitet die Tränenflüssigkeit ab, die das Auge befeuchtet und schützt.',
  nu=['Omega-3-Fettsäuren','Vitamin A','Wasser'], su=['Omega-3','Vitamin A bei Mangel'],
  di=[('Trockenes Auge','Tränenersatzmittel, Ciclosporin-Tropfen'),('Tränenwegsverschluss','Spülung, Operation (DCR)'),('Dakryozystitis','Antibiotika (Amoxicillin/Clavulansäure)'),('Dakryoadenitis','NSAR, Kortikosteroide')]),
 'eyelid': dict(d='{n} gehört zum Augenlid. Lider schützen das Auge, verteilen den Tränenfilm und enthalten Talgdrüsen.',
  nu=['Omega-3-Fettsäuren','Vitamin A','Zink'], su=['Omega-3'],
  di=[('Blepharitis','Lidrandhygiene, Antibiotika-Salbe'),('Gerstenkorn / Hagelkorn','Warme Kompressen, Antibiotika-Salbe, ggf. Inzision'),('Ptosis','Operation'),('Basaliom am Lid','Operation')]),
 'ear': dict(d='{n} gehört zum Ohr. Das äußere Ohr fängt Schall auf und leitet ihn zum Trommelfell.',
  nu=['Zink','Magnesium','Vitamin B12','Omega-3'], su=['Magnesium','Vitamin B12 bei Mangel'],
  di=[('Gehörgangsentzündung (Otitis externa)','Antibiotische Ohrentropfen (Ciprofloxacin), Kortikosteroid-Tropfen'),('Ohrenschmalzpfropf','Cerumenolytika, Spülung'),('Perichondritis der Ohrmuschel','Ciprofloxacin')]),
 'airway': dict(d='{n} gehört zu den Atemwegen{loc}. Die Atemwege leiten, erwärmen und reinigen die Atemluft auf dem Weg zur Lunge.',
  nu=['Vitamin C','Vitamin D','Omega-3','Zink','Antioxidantien','Flüssigkeit'], su=['Vitamin D3','N-Acetylcystein','Zink bei Erkältung'],
  di=[('Bronchitis','Schleimlöser (Acetylcystein), bei Bakterien Amoxicillin'),('Asthma','Salbutamol, inhalatives Kortikosteroid (Budesonid), Montelukast'),('COPD','Tiotropium, Formoterol, Rauchstopp'),('Lungenentzündung','Amoxicillin, Doxycyclin, Levofloxacin'),('Bronchialkarzinom','Operation, Chemo-/Immuntherapie (Pembrolizumab)')]),
 'lung': dict(d='{n} ist ein Lungensegment{loc}: eine eigenständig versorgte Einheit der Lunge mit eigenem Bronchus und eigener Arterie, in der der Gasaustausch stattfindet.',
  nu=['Vitamin C','Vitamin D','Vitamin A','Omega-3','Antioxidantien'], su=['Vitamin D3','N-Acetylcystein'],
  di=[('Lungenentzündung','Amoxicillin, Doxycyclin, Levofloxacin'),('Lungenembolie','Heparin, DOAK'),('Lungenkarzinom','Operation, Immuntherapie, Chemotherapie'),('Tuberkulose','Isoniazid, Rifampicin, Pyrazinamid, Ethambutol'),('COPD / Emphysem','Tiotropium, Formoterol')]),
 'larynx': dict(d='{n} gehört zum Kehlkopf{loc}. Der Kehlkopf schützt die Atemwege beim Schlucken und erzeugt die Stimme.',
  nu=['Wasser','Vitamin C','Vitamin A','Zink'], su=['Vitamin D3'],
  di=[('Kehlkopfentzündung (Laryngitis)','Stimmschonung, Inhalation, bei Bakterien Antibiotika'),('Stimmlippenknötchen / -polypen','Logopädie, ggf. Operation'),('Kehlkopfkrebs','Operation, Strahlentherapie'),('Reflux-Laryngitis','Pantoprazol')]),
 'nose': dict(d='{n} gehört zur Nase{loc}. Die Nase erwärmt, befeuchtet und filtert die Atemluft und trägt das Riechorgan.',
  nu=['Vitamin C','Zink','Vitamin A','Flüssigkeit'], su=['Zink','Vitamin D3'],
  di=[('Schnupfen / allergische Rhinitis','Antihistaminika (Cetirizin), Kortikosteroid-Nasenspray (Mometason)'),('Nasennebenhöhlenentzündung','Kortikosteroid-Spray, Salzlösung, bei Bakterien Amoxicillin'),('Nasenpolypen','Kortikosteroid-Spray, Dupilumab, Operation'),('Septumdeviation','Operation (Septumplastik)')]),
 'pharynx': dict(d='{n} gehört zum Rachen{loc}. Der Rachen ist gemeinsamer Weg für Luft und Nahrung und leitet den Schluckakt ein.',
  nu=['Vitamin C','Zink','Flüssigkeit','Eiweiß'], su=['Zink bei Erkältung'],
  di=[('Rachenentzündung / Mandelentzündung','Schmerzmittel, bei Streptokokken Penicillin V'),('Schluckstörung (Dysphagie)','Logopädie, Ursache behandeln'),('Schlafapnoe','CPAP-Maske, Gewichtsreduktion'),('Rachenkrebs','Operation, Strahlen-/Chemotherapie')]),
 'mouth': dict(d='{n} gehört zum Mund{loc}. Mund, Zunge und Gaumen zerkleinern Nahrung, ermöglichen Sprache und Geschmack.',
  nu=['B-Vitamine','Eisen','Zink','Vitamin C','Folat'], su=['Vitamin B12 bei Mangel','Zink'],
  di=[('Aphthen / Stomatitis','Lokale Kortikosteroide, Chlorhexidin'),('Mundsoor','Nystatin, Fluconazol'),('Glossitis (Zungenentzündung)','B-Vitamine, Eisen'),('Mundhöhlenkrebs','Operation, Strahlentherapie')]),
 'salivary': dict(d='{n} ist eine Speicheldrüse. Speichel befeuchtet die Nahrung, beginnt die Verdauung und schützt Zähne und Schleimhaut.',
  nu=['Wasser','Vitamin C','Zink'], su=[],
  di=[('Speicheldrüsenentzündung (Sialadenitis)','Antibiotika (Amoxicillin/Clavulansäure), Speichelanregung'),('Speichelstein','Massage, Sialendoskopie, Operation'),('Mumps','Symptomatisch, Impfung zur Vorbeugung'),('Sjögren-Syndrom','Pilocarpin, Speichelersatz')]),
 'esophagus': dict(d='{n} ist die Speiseröhre. Sie befördert Nahrung durch wellenförmige Muskelbewegungen vom Rachen in den Magen.',
  nu=['Ballaststoffe','Eiweiß','Zink','Vitamin C'], su=[],
  di=[('Refluxkrankheit','Protonenpumpenhemmer (Pantoprazol, Omeprazol)'),('Ösophagitis','PPI, bei Pilz Fluconazol'),('Achalasie','Ballondilatation, Botulinumtoxin, Operation'),('Speiseröhrenkrebs','Operation, Chemo-/Strahlentherapie')]),
 'stomach': dict(d='{n} ist der Magen. Er speichert Nahrung, vermischt sie mit Säure und Enzymen und gibt den Brei portionsweise an den Zwölffingerdarm ab.',
  nu=['Eiweiß','Vitamin B12','Eisen','Zink','Ballaststoffe'], su=['Vitamin B12 bei PPI-Einnahme oder Mangel','Probiotika (Evidenz begrenzt)'],
  di=[('Gastritis','Pantoprazol, Auslöser meiden'),('Magengeschwür / Helicobacter','PPI + Amoxicillin + Clarithromycin'),('Reizmagen','Iberogast, Ernährungsumstellung'),('Magenkrebs','Operation, Chemotherapie')]),
 'small_intestine': dict(d='{n} gehört zum Dünndarm{loc}. Hier werden Nährstoffe enzymatisch aufgeschlossen und über die Darmzotten ins Blut aufgenommen.',
  nu=['Ballaststoffe','Vitamin B12 (Aufnahme im Ileum)','Eisen','Folat','Zink','Vitamin D'], su=['Vitamin B12','Eisen bei Mangel','Probiotika (Evidenz begrenzt)'],
  di=[('Zöliakie','Glutenfreie Ernährung'),('Morbus Crohn','Mesalazin, Kortikosteroide (Budesonid), Azathioprin, Adalimumab'),('Zwölffingerdarmgeschwür','PPI, Helicobacter-Therapie'),('Darmverschluss (Ileus)','Notfall, Operation'),('Bakterielle Fehlbesiedlung','Rifaximin')]),
 'colon': dict(d='{n} gehört zum Dickdarm{loc}. Der Dickdarm entzieht dem Nahrungsbrei Wasser und Salze und beherbergt die Darmflora.',
  nu=['Ballaststoffe','Wasser','Calcium','Vitamin D','Fermentierte Lebensmittel'], su=['Flohsamenschalen','Probiotika','Vitamin D3'],
  di=[('Colitis ulcerosa','Mesalazin, Kortikosteroide, Infliximab, Vedolizumab'),('Divertikulitis','Antibiotika (Ciprofloxacin + Metronidazol), Ballaststoffe'),('Reizdarmsyndrom','Mebeverin, Flohsamen, FODMAP-arme Ernährung'),('Dickdarmkrebs','Operation, Chemotherapie (FOLFOX), Vorsorge-Koloskopie'),('Verstopfung','Macrogol, Ballaststoffe, Flüssigkeit')]),
 'rectum': dict(d='{n} ist der Mastdarm bzw. Enddarm. Er speichert den Stuhl und steuert mit dem Schließmuskel die Entleerung.',
  nu=['Ballaststoffe','Wasser'], su=['Flohsamenschalen'],
  di=[('Hämorrhoiden','Salben (Lidocain), Ballaststoffe, Verödung, Ligatur'),('Analfissur','Nitroglycerin-Salbe, Diltiazem-Salbe'),('Proktitis','Mesalazin-Zäpfchen'),('Rektumkarzinom','Operation, Radiochemotherapie')]),
 'appendix': dict(d='{n} gehört zum Wurmfortsatz am Blinddarm. Er enthält lymphatisches Gewebe und spielt eine Rolle für das Immunsystem des Darms.',
  nu=['Ballaststoffe','Wasser'], su=[],
  di=[('Appendizitis (Blinddarmentzündung)','Operation, Antibiotika (Ceftriaxon + Metronidazol)'),('Appendix-Tumor (Karzinoid)','Operation')]),
 'liver': dict(d='{n} gehört zur Leber{loc}. Die Leber verstoffwechselt Nährstoffe, entgiftet, bildet Galle und Bluteiweiße und speichert Glykogen.',
  nu=['Eiweiß','Cholin','Vitamin B12','Folat','Vitamin D','Kaffee (schützend)','wenig Alkohol'], su=['Vitamin D3','Vitamin E bei Fettleber (nach Rücksprache)','Silymarin (Evidenz begrenzt)'],
  di=[('Fettleber','Gewichtsreduktion, Bewegung, Alkoholverzicht; Resmetirom (neu)'),('Virushepatitis B/C','Entecavir/Tenofovir; Sofosbuvir-Kombinationen'),('Leberzirrhose','Spironolacton, Lactulose, Propranolol'),('Leberkrebs','Operation, Atezolizumab + Bevacizumab, Sorafenib')]),
 'biliary': dict(d='{n} gehört zum Gallenwegssystem{loc}. Die Gallenwege sammeln die in der Leber gebildete Galle und leiten sie in den Zwölffingerdarm.',
  nu=['Ballaststoffe','Ungesättigte Fette','Vitamin C','Magnesium'], su=['Ursodesoxycholsäure (nur ärztlich)'],
  di=[('Gallensteine','Ursodesoxycholsäure, Operation (Cholezystektomie)'),('Gallenblasenentzündung','Antibiotika (Ceftriaxon + Metronidazol), Operation'),('Gallengangsverschluss / Cholangitis','ERCP, Antibiotika'),('Primär biliäre Cholangitis','Ursodesoxycholsäure, Obeticholsäure')]),
 'pancreas': dict(d='{n} gehört zur Bauchspeicheldrüse. Sie bildet Verdauungsenzyme für den Dünndarm und Hormone wie Insulin und Glukagon.',
  nu=['Ballaststoffe','Vollkorn','Magnesium','Vitamin D','Zink','wenig Zucker und Alkohol'], su=['Vitamin D3','Pankreasenzyme bei Insuffizienz (ärztlich)'],
  di=[('Diabetes mellitus','Metformin, SGLT2-Hemmer (Empagliflozin), GLP-1-Agonisten (Semaglutid), Insulin'),('Akute Pankreatitis','Flüssigkeit, Schmerztherapie, Nahrungskarenz'),('Chronische Pankreatitis','Pankreatin, Schmerzmittel, Alkoholverzicht'),('Bauchspeicheldrüsenkrebs','Operation, Chemotherapie (FOLFIRINOX)')]),
 'peritoneum': dict(d='{n} gehört zum Bauchfell bzw. Gekröse. Es überzieht die Bauchorgane, hält sie beweglich und führt ihre Gefäße und Nerven.',
  nu=['Eiweiß','Wasser'], su=[],
  di=[('Peritonitis','Breitband-Antibiotika (Piperacillin/Tazobactam), Operation'),('Aszites','Diuretika (Spironolacton, Furosemid)'),('Mesenterialischämie','Notfall-Operation, Antikoagulation'),('Peritonealkarzinose','Chemotherapie, HIPEC')]),
 'kidney': dict(d='{n} ist eine Niere. Die Nieren filtern das Blut, scheiden Harn aus, regulieren Blutdruck, Salz- und Wasserhaushalt und bilden Hormone.',
  nu=['Wasser','Kalium (angepasst)','wenig Salz','Vitamin D','Omega-3','Eiweiß in Maßen'], su=['Vitamin D3','Omega-3'],
  di=[('Chronische Nierenkrankheit','ACE-Hemmer (Ramipril), SGLT2-Hemmer (Dapagliflozin), Finerenon'),('Nierensteine','Schmerzmittel (Diclofenac), Tamsulosin, viel trinken'),('Nierenbeckenentzündung','Ciprofloxacin, Ceftriaxon'),('Glomerulonephritis','Kortikosteroide, Immunsuppressiva'),('Nierenzellkarzinom','Operation, Immuntherapie (Pembrolizumab)')]),
 'ureter': dict(d='{n} ist ein Harnleiter. Er leitet den Harn mit wellenförmigen Bewegungen von der Niere zur Harnblase.',
  nu=['Wasser','wenig Salz','Citrat (Zitrusfrüchte)'], su=['Kaliumcitrat bei Steinneigung (ärztlich)'],
  di=[('Harnleiterstein','Diclofenac, Tamsulosin, Ureteroskopie'),('Harnleiterverengung','Stent, Operation'),('Reflux (Kinder)','Antibiotikaprophylaxe, Operation')]),
 'bladder': dict(d='{n} ist die Harnblase. Sie speichert den Harn und entleert sich über die Harnröhre.',
  nu=['Wasser','Cranberry (begrenzte Evidenz)','Vitamin D'], su=['D-Mannose (Evidenz begrenzt)','Cranberry-Extrakt'],
  di=[('Blasenentzündung','Fosfomycin, Nitrofurantoin, Pivmecillinam'),('Überaktive Blase','Solifenacin, Mirabegron, Beckenbodentraining'),('Blasenkrebs','Operation (TUR), BCG-Instillation, Chemotherapie'),('Harnverhalt','Katheter, Tamsulosin')]),
 'urethra': dict(d='{n} ist die Harnröhre. Sie leitet den Harn aus der Blase nach außen; beim Mann führt sie auch das Ejakulat.',
  nu=['Wasser'], su=[],
  di=[('Harnröhrenentzündung','Doxycyclin, Azithromycin, Ceftriaxon (bei Gonorrhö)'),('Harnröhrenstriktur','Dehnung, Operation'),('Harninkontinenz','Beckenbodentraining, Duloxetin, Operation')]),
 'testis': dict(d='{n} gehört zu den Hoden. Sie bilden Spermien und das Hormon Testosteron.',
  nu=['Zink','Selen','Folat','Vitamin D','Omega-3','Antioxidantien'], su=['Zink','Selen','Vitamin D3','Coenzym Q10 (bei Fruchtbarkeitsproblemen, Evidenz begrenzt)'],
  di=[('Hodenentzündung (Orchitis)','Antibiotika (Ceftriaxon, Doxycyclin), NSAR'),('Hodentorsion','Notfall-Operation'),('Hodenkrebs','Operation, Cisplatin-Chemotherapie'),('Hypogonadismus','Testosteron-Ersatz'),('Varikozele','Operation bei Beschwerden')]),
 'epididymis': dict(d='{n} ist ein Nebenhoden. Hier reifen die Spermien und werden bis zur Ejakulation gespeichert.',
  nu=['Zink','Selen','Vitamin C'], su=['Zink'],
  di=[('Nebenhodenentzündung','Ceftriaxon + Doxycyclin, NSAR, Hochlagerung'),('Spermatozele','Operation bei Beschwerden')]),
 'genital_duct': dict(d='{n} gehört zu den ableitenden Samenwegen. Er transportiert Spermien bzw. bildet Bestandteile der Samenflüssigkeit.',
  nu=['Zink','Fruktose (Samenblase)','Vitamin C'], su=['Zink'],
  di=[('Entzündung der Samenwege (Vesikulitis)','Antibiotika'),('Verschluss (z. B. nach Vasektomie)','Mikrochirurgische Wiederherstellung')]),
 'prostate': dict(d='{n} ist die Vorsteherdrüse. Sie bildet einen Teil der Samenflüssigkeit und umgibt den Anfang der Harnröhre.',
  nu=['Lycopin (Tomaten)','Zink','Selen','Omega-3','Kreuzblütler-Gemüse'], su=['Sägepalmenextrakt (begrenzte Evidenz)','Kürbiskernextrakt','Zink'],
  di=[('Gutartige Prostatavergrößerung','Tamsulosin, Finasterid, Operation (TUR-P)'),('Prostatitis','Ciprofloxacin, NSAR'),('Prostatakrebs','Operation, Strahlentherapie, Antiandrogene (Enzalutamid)')]),
 'penis': dict(d='{n} gehört zu den Schwellkörpern des Penis. Sie füllen sich bei Erregung mit Blut und ermöglichen die Erektion.',
  nu=['Nitratreiches Gemüse','Omega-3','L-Arginin','Zink'], su=['L-Arginin/L-Citrullin (Evidenz begrenzt)'],
  di=[('Erektile Dysfunktion','Sildenafil, Tadalafil'),('Induratio penis plastica','Kollagenase, Operation'),('Priapismus','Notfall: Punktion, Phenylephrin'),('Balanitis','Antimykotika (Clotrimazol), Hygiene')]),
 'adrenal': dict(d='{n} ist eine Nebenniere. Ihre Rinde bildet Cortisol, Aldosteron und Androgene, ihr Mark Adrenalin und Noradrenalin.',
  nu=['Vitamin C','Vitamin B5','Magnesium','Eiweiß'], su=['Vitamin C','Magnesium'],
  di=[('Morbus Addison (Unterfunktion)','Hydrocortison, Fludrocortison'),('Cushing-Syndrom','Operation, Ketoconazol, Osilodrostat'),('Conn-Syndrom (Hyperaldosteronismus)','Spironolacton, Operation'),('Phäochromozytom','Alpha-Blocker (Phenoxybenzamin), Operation')]),
 'pituitary': dict(d='{n} ist die Hirnanhangsdrüse. Sie steuert über ihre Hormone Schilddrüse, Nebennieren, Keimdrüsen, Wachstum, Milchbildung und Wasserhaushalt.',
  nu=['Jod','Eiweiß','Zink','Vitamin D'], su=[],
  di=[('Prolaktinom','Cabergolin'),('Akromegalie','Operation, Octreotid'),('Hypophyseninsuffizienz','Hormonersatz (Hydrocortison, Levothyroxin, Testosteron)'),('Diabetes insipidus','Desmopressin')]),
 'pineal': dict(d='{n} ist die Zirbeldrüse. Sie bildet nachts Melatonin und steuert damit den Tag-Nacht-Rhythmus.',
  nu=['Tryptophan','Magnesium','Vitamin B6'], su=['Melatonin bei Jetlag oder Einschlafstörung'],
  di=[('Schlaf-Wach-Rhythmusstörung','Melatonin, Lichttherapie'),('Pinealiszyste / -tumor','Beobachtung, Operation')]),
 'spleen': dict(d='{n} ist die Milz. Sie filtert das Blut, baut alte Blutzellen ab, speichert Blutplättchen und bildet Abwehrzellen.',
  nu=['Eisen','Folat','Vitamin B12','Vitamin C'], su=['Eisen bei Mangel'],
  di=[('Milzvergrößerung (Splenomegalie)','Ursache behandeln (Infektion, Leber, Blutbild)'),('Milzruptur','Notfall-Operation'),('Asplenie (nach Entfernung)','Impfungen (Pneumokokken, Meningokokken), Penicillin-Prophylaxe'),('Hypersplenismus','Ursache behandeln, ggf. Splenektomie')]),
 'thymus': dict(d='{n} gehört zum Thymus. Hier reifen in der Kindheit die T-Lymphozyten des Immunsystems; im Erwachsenenalter bildet er sich zurück.',
  nu=['Zink','Vitamin D','Eiweiß','Selen'], su=['Zink','Vitamin D3'],
  di=[('Myasthenia gravis (Thymusbeteiligung)','Pyridostigmin, Kortikosteroide, Thymektomie'),('Thymom','Operation, Strahlentherapie')]),
 'heart_chamber': dict(d='{n} gehört zum Herzen{loc}. Vorhöfe nehmen Blut auf, Kammern pumpen es in Lungen- und Körperkreislauf.',
  nu=['Kalium','Magnesium','Omega-3-Fettsäuren','wenig Salz','Coenzym Q10 (Nahrung)'], su=['Omega-3','Magnesium','Coenzym Q10 (Evidenz begrenzt)'],
  di=[('Herzinsuffizienz','ACE-Hemmer/Sacubitril-Valsartan, Betablocker, SGLT2-Hemmer, Diuretika'),('Vorhofflimmern','Apixaban, Betablocker, Ablation'),('Herzinfarkt','ASS, Heparin, Stent, Statine'),('Kardiomyopathie','Betablocker, ACE-Hemmer, ICD'),('Myokarditis','Schonung, Herzinsuffizienz-Therapie')]),
 'valve': dict(d='{n} gehört zu den Herzklappen{loc}. Die Klappen wirken als Ventile und lenken den Blutstrom in eine Richtung.',
  nu=['Kalium','Magnesium','Vitamin K2','Omega-3'], su=['Vitamin K2 (Evidenz begrenzt)','Omega-3'],
  di=[('Klappenstenose','Klappenersatz (TAVI, Operation)'),('Klappeninsuffizienz','Diuretika, ACE-Hemmer, Rekonstruktion'),('Endokarditis','Antibiotika i. v. (Penicillin, Vancomycin)'),('Rheumatisches Fieber','Penicillin, NSAR')]),
 'skin': dict(d='{n} gehört zur Haut. Die Haut schützt vor Austrocknung, Keimen und UV-Licht, regelt die Temperatur und nimmt Berührung wahr.',
  nu=['Vitamin A','Vitamin C','Vitamin E','Zink','Omega-3','Biotin','Wasser'], su=['Omega-3','Zink','Vitamin D3'],
  di=[('Ekzem / Neurodermitis','Kortikosteroid-Cremes, Pflege, Dupilumab'),('Akne','Benzoylperoxid, Adapalen, Isotretinoin'),('Psoriasis','Vitamin-D-Analoga, Methotrexat, Biologika'),('Hautkrebs','Operation, bei Melanom Immuntherapie'),('Hautinfektionen','Antibiotika (Cefalexin), Antimykotika')]),
 'hair': dict(d='{n} gehört zum Haarkleid. Haare schützen vor Kälte, UV-Licht und Reibung und dienen der Wahrnehmung.',
  nu=['Eiweiß','Eisen','Zink','Biotin','Vitamin D','Omega-3'], su=['Eisen bei Mangel','Biotin (nur bei Mangel wirksam)','Zink'],
  di=[('Androgenetischer Haarausfall','Minoxidil, Finasterid'),('Kreisrunder Haarausfall','Kortikosteroide, JAK-Hemmer (Baricitinib)'),('Kopfhautpilz','Terbinafin, Griseofulvin'),('Läuse','Dimeticon, Permethrin')]),
 'lip': dict(d='{n} ist die Lippe. Lippen formen Laute, halten Nahrung im Mund und sind sehr berührungsempfindlich.',
  nu=['B-Vitamine','Eisen','Wasser'], su=['Vitamin B2 bei Mundwinkelrhagaden'],
  di=[('Herpes labialis','Aciclovir-Creme, Valaciclovir'),('Cheilitis','Pflege, B-Vitamine, Antimykotika'),('Lippenkrebs (Sonnenlicht)','Operation, UV-Schutz')]),
 'meninges': dict(d='{n} gehört zu den Hirnhäuten bzw. Liquorräumen. Sie umhüllen und polstern Gehirn und Rückenmark.',
  nu=['Wasser','Vitamin B12'], su=[],
  di=[('Meningitis','Ceftriaxon, Ampicillin, Dexamethason'),('Subarachnoidalblutung','Nimodipin, Aneurysma-Verschluss'),('Subduralhämatom','Operation'),('Meningeom','Operation, Strahlentherapie')]),
 'region': dict(d='{n} ist eine Körperregion bzw. topografische Einheit{loc}. Solche Gruppierungen fassen die Strukturen eines Bereichs zusammen.',
  nu=['Ausgewogene Ernährung: Eiweiß, Vitamine, Mineralstoffe'], su=['Vitamin D3 (allgemein häufiger Mangel)'],
  di=[('Verletzungen der Region','Kühlung, Schmerzmittel, Ruhigstellung'),('Infektionen','Antibiotika je nach Erreger'),('Erkrankungen der enthaltenen Organe','siehe jeweilige Struktur')]),
 'compartment': dict(d='{n} ist eine Muskelloge{loc}: ein von Faszien umschlossener Raum mit Muskeln, Gefäßen und Nerven gleicher Funktion.',
  nu=['Eiweiß','Magnesium','Kalium','Wasser'], su=['Magnesium'],
  di=[('Kompartmentsyndrom','Notfall-Fasziotomie'),('Muskelverletzungen','NSAR, Physiotherapie'),('Chronisches Belastungs-Kompartmentsyndrom','Trainingsanpassung, Fasziotomie')]),
 'abstract': dict(d='{n} ist ein übergeordneter Ordnungsbegriff der anatomischen Klassifikation (FMA) und bezeichnet keine einzelne Körperstruktur.',
  nu=[], su=[], di=[]),
}
