# english base -> (german adj stems, german noun, gender, latin nominative, latin genitive)
# gender: m/f/n/p(plural). German genitive is built by rules + NOUN_GEN overrides.
B = {
 'abdomen':('','Bauch','m','Abdomen','abdominis'),
 'abdomen proper':('eigentlich','Bauch','m','Abdomen proprium','abdominis proprii'),
 'anterior abdominal wall':('vorder','Bauchwand','f','Paries abdominis anterior','parietis abdominis anterioris'),
 'posterior abdominal wall':('hinter','Bauchwand','f','Paries abdominis posterior','parietis abdominis posterioris'),
 'arm':('','Oberarm','m','Brachium','brachii'),
 'forearm':('','Unterarm','m','Antebrachium','antebrachii'),
 'wrist':('','Handgelenk','n','Carpus','carpi'),
 'hand':('','Hand','f','Manus','manus'),
 'hand proper':('eigentlich','Hand','f','Manus propria','manus propriae'),
 'shoulder':('','Schulter','f','Regio deltoidea','regionis deltoideae'),
 'upper limb':('ober','Gliedmaße','f','Membrum superius','membri superioris'),
 'lower limb':('unter','Gliedmaße','f','Membrum inferius','membri inferioris'),
 'free upper limb':('frei ober','Gliedmaße','f','Pars libera membri superioris','partis liberae membri superioris'),
 'free lower limb':('frei unter','Gliedmaße','f','Pars libera membri inferioris','partis liberae membri inferioris'),
 'limb':('','Gliedmaße','f','Membrum','membri'),
 'thigh':('','Oberschenkel','m','Femur','femoris'),
 'knee':('','Knie','n','Genu','genus'),
 'leg':('','Unterschenkel','m','Crus','cruris'),
 'foot':('','Fuß','m','Pes','pedis'),
 'foot proper':('eigentlich','Fuß','m','Pes proprius','pedis proprii'),
 'hip':('','Hüfte','f','Coxa','coxae'),
 'thumb':('','Daumen','m','Pollex','pollicis'),
 'index finger':('','Zeigefinger','m','Index','indicis'),
 'middle finger':('','Mittelfinger','m','Digitus medius','digiti medii'),
 'ring finger':('','Ringfinger','m','Digitus anularis','digiti anularis'),
 'little finger':('','Kleinfinger','m','Digitus minimus manus','digiti minimi manus'),
 'finger':('','Finger','m','Digitus manus','digiti manus'),
 'big toe':('','Großzehe','f','Hallux','hallucis'),
 'second toe':('zweit','Zehe','f','Digitus secundus pedis','digiti secundi pedis'),
 'third toe':('dritt','Zehe','f','Digitus tertius pedis','digiti tertii pedis'),
 'fourth toe':('viert','Zehe','f','Digitus quartus pedis','digiti quarti pedis'),
 'little toe':('','Kleinzehe','f','Digitus minimus pedis','digiti minimi pedis'),
 'toe':('','Zehe','f','Digitus pedis','digiti pedis'),
 'head':('','Kopf','m','Caput','capitis'),
 'head proper':('eigentlich','Kopf','m','Caput proprium','capitis proprii'),
 'auriculotemporal part of head':('','Ohr-Schläfen-Region des Kopfes','f','Pars auriculotemporalis capitis','partis auriculotemporalis capitis'),
 'face':('','Gesicht','n','Facies','faciei'),
 'cheek':('','Wange','f','Bucca','buccae'),
 'neck':('','Hals','m','Collum','colli'),
 'trunk':('','Rumpf','m','Truncus','trunci'),
 'thorax':('','Brustkorb','m','Thorax','thoracis'),
 'chest':('','Brust','f','Pectus','pectoris'),
 'pelvis':('','Becken','n','Pelvis','pelvis'),
 'perineum':('','Damm','m','Perineum','perinei'),
 'mediastinum':('','Mittelfellraum','m','Mediastinum','mediastini'),
 'anterior mediastinum':('vorder','Mittelfellraum','m','Mediastinum anterius','mediastini anterioris'),
 'posterior mediastinum':('hinter','Mittelfellraum','m','Mediastinum posterius','mediastini posterioris'),
 'superior mediastinum':('ober','Mittelfellraum','m','Mediastinum superius','mediastini superioris'),
 'inferior mediastinum':('unter','Mittelfellraum','m','Mediastinum inferius','mediastini inferioris'),
 'middle mediastinum':('mittler','Mittelfellraum','m','Mediastinum medium','mediastini medii'),
 'pectoral girdle':('','Schultergürtel','m','Cingulum pectorale','cinguli pectoralis'),
 'pelvic girdle':('','Beckengürtel','m','Cingulum pelvicum','cinguli pelvici'),
 'bony pelvis':('knöchern','Becken','n','Pelvis ossea','pelvis osseae'),
 'rib cage':('','Brustkorbskelett','n','Cavea thoracis','caveae thoracis'),
 'sternum':('','Brustbein','n','Sternum','sterni'),
 'vertebral column':('','Wirbelsäule','f','Columna vertebralis','columnae vertebralis'),
 'cervical vertebra':('','Halswirbel','m','Vertebra cervicalis','vertebrae cervicalis'),
 'thoracic vertebra':('','Brustwirbel','m','Vertebra thoracica','vertebrae thoracicae'),
 'lumbar vertebra':('','Lendenwirbel','m','Vertebra lumbalis','vertebrae lumbalis'),
 'cervical vertebrae':('','Halswirbel','p','Vertebrae cervicales','vertebrarum cervicalium'),
 'thoracic vertebrae':('','Brustwirbel','p','Vertebrae thoracicae','vertebrarum thoracicarum'),
 'lumbar vertebrae':('','Lendenwirbel','p','Vertebrae lumbales','vertebrarum lumbalium'),
 'symphysis':('','Symphyse','f','Symphysis','symphysis'),
 'bone organ':('','Knochen','m','Os','ossis'),
 'muscle organ':('','Muskel','m','Musculus','musculi'),
 'muscle layer':('','Muskelschicht','f','Tunica muscularis','tunicae muscularis'),
 'organ':('','Organ','n','Organum','organi'),
 'organs':('','Organe','p','Organa','organorum'),
 'organ part':('','Organteil','m','Pars organi','partis organi'),
 'organ parts':('','Organteile','p','Partes organi','partium organi'),
 'organ regions':('','Organregionen','p','Regiones organi','regionum organi'),
 'organ component':('','Organkomponente','f','Componens organi','componentis organi'),
 'cardinal body part':('','Körperhauptteil','m','Pars cardinalis corporis','partis cardinalis corporis'),
 'cavernous organ':('','Schwellkörperorgan','n','Organum cavernosum','organi cavernosi'),
 'corpus spongiosum of penis':('','Harnröhrenschwellkörper','m','Corpus spongiosum penis','corporis spongiosi penis'),
 'continuity':('','Kontinuität','f','Continuitas','continuitatis'),
 'heterogeneous clusters':('heterogen','Cluster','p','Aggregata heterogenea','aggregatorum heterogeneorum'),
 'hairs':('','Haare','p','Pili','pilorum'),
 'facial hairs':('','Gesichtshaare','p','Pili faciei','pilorum faciei'),
 'epidermis':('','Oberhaut','f','Epidermis','epidermidis'),
 'epithelium':('','Epithel','n','Epithelium','epithelii'),
 'serous membrane':('serös','Haut','f','Tunica serosa','tunicae serosae'),
 'peritoneum':('','Bauchfell','n','Peritoneum','peritonei'),
 'visceral peritoneum':('viszeral','Bauchfell','n','Peritoneum viscerale','peritonei visceralis'),
 'dura mater':('hart','Hirnhaut','f','Dura mater','durae matris'),
 'cranial dura mater':('hart','Hirnhaut','f','Dura mater cranialis','durae matris cranialis'),
 'subarachnoid space':('','Subarachnoidalraum','m','Spatium subarachnoideum','spatii subarachnoidei'),
 'fascia lata':('','Oberschenkelfaszie','f','Fascia lata','fasciae latae'),
 'investing fascia':('','Hüllfaszie','f','Fascia investiens','fasciae investientis'),
 'investing fascia of thigh':('','Hüllfaszie des Oberschenkels','f','Fascia investiens femoris','fasciae investientis femoris'),
 'investing fascia of lower limb':('','Hüllfaszie der unteren Gliedmaße','f','Fascia investiens membri inferioris','fasciae investientis membri inferioris'),
 'investing fascia of free lower limb':('','Hüllfaszie der freien unteren Gliedmaße','f','Fascia investiens partis liberae membri inferioris','fasciae investientis partis liberae membri inferioris'),
 # compartments
 'anterior compartment of arm':('vorder','Oberarmloge','f','Compartimentum brachii anterius','compartimenti brachii anterioris'),
 'posterior compartment of arm':('hinter','Oberarmloge','f','Compartimentum brachii posterius','compartimenti brachii posterioris'),
 'anterior compartment of forearm':('vorder','Unterarmloge','f','Compartimentum antebrachii anterius','compartimenti antebrachii anterioris'),
 'posterior compartment of forearm':('hinter','Unterarmloge','f','Compartimentum antebrachii posterius','compartimenti antebrachii posterioris'),
 'anterior compartment of thigh':('vorder','Oberschenkelloge','f','Compartimentum femoris anterius','compartimenti femoris anterioris'),
 'posterior compartment of thigh':('hinter','Oberschenkelloge','f','Compartimentum femoris posterius','compartimenti femoris posterioris'),
 'medial compartment of thigh':('medial','Oberschenkelloge','f','Compartimentum femoris mediale','compartimenti femoris medialis'),
 'anterior compartment of leg':('vorder','Unterschenkelloge','f','Compartimentum cruris anterius','compartimenti cruris anterioris'),
 'posterior compartment of leg':('hinter','Unterschenkelloge','f','Compartimentum cruris posterius','compartimenti cruris posterioris'),
 'lateral compartment of leg':('seitlich','Unterschenkelloge','f','Compartimentum cruris laterale','compartimenti cruris lateralis'),
 # head/neck organs
 'mouth':('','Mund','m','Os','oris'),
 'palate':('','Gaumen','m','Palatum','palati'),
 'tongue':('','Zunge','f','Lingua','linguae'),
 'pharynx':('','Rachen','m','Pharynx','pharyngis'),
 'laryngopharynx':('','Kehlkopfrachen','m','Laryngopharynx','laryngopharyngis'),
 'larynx':('','Kehlkopf','m','Larynx','laryngis'),
 'nose':('','Nase','f','Nasus','nasi'),
 'external nose':('äußer','Nase','f','Nasus externus','nasi externi'),
 'internal nose':('inner','Nase','f','Nasus internus','nasi interni'),
 'side of internal nose':('','Seite der inneren Nase','f','Latus nasi interni','lateris nasi interni'),
 'nasal septum':('','Nasenscheidewand','f','Septum nasi','septi nasi'),
 'eye':('','Auge','n','Oculus','oculi'),
 'eyeball':('','Augapfel','m','Bulbus oculi','bulbi oculi'),
 'retina':('','Netzhaut','f','Retina','retinae'),
 'ciliary body':('','Ziliarkörper','m','Corpus ciliare','corporis ciliaris'),
 'layer of wall of eyeball':('','Schicht der Augapfelwand','f','Tunica bulbi oculi','tunicae bulbi oculi'),
 'vascular layer of eyeball':('','Gefäßhaut des Augapfels','f','Tunica vasculosa bulbi','tunicae vasculosae bulbi'),
 'lacrimal duct':('','Tränengang','m','Ductus lacrimalis','ductus lacrimalis'),
 'ciliary ganglion':('','Ziliarganglion','n','Ganglion ciliare','ganglii ciliaris'),
 'cranial nerve':('','Hirnnerv','m','Nervus cranialis','nervi cranialis'),
 'frontal nerve':('','Stirnnerv','m','Nervus frontalis','nervi frontalis'),
 'nasociliary nerve':('','Nasoziliarnerv','m','Nervus nasociliaris','nervi nasociliaris'),
 'oculomotor nerve':('','Augenbewegungsnerv','m','Nervus oculomotorius','nervi oculomotorii'),
 'ophthalmic nerve':('','Augennerv','m','Nervus ophthalmicus','nervi ophthalmici'),
 'trigeminal nerve':('','Drillingsnerv','m','Nervus trigeminus','nervi trigemini'),
 # brain
 'brain':('','Gehirn','n','Encephalon','encephali'),
 'neuraxis':('','Neuraxis','f','Neuraxis','neuraxis'),
 'nervous system':('','Nervensystem','n','Systema nervosum','systematis nervosi'),
 'parasympathetic nervous system':('parasympathisch','Nervensystem','n','Pars parasympathica','partis parasympathicae'),
 'neural tree organ':('','Nervenbaumorgan','n','Organum arboris nervosae','organi arboris nervosae'),
 'forebrain':('','Vorderhirn','n','Prosencephalon','prosencephali'),
 'hindbrain':('','Rautenhirn','n','Rhombencephalon','rhombencephali'),
 'midbrain':('','Mittelhirn','n','Mesencephalon','mesencephali'),
 'midbrain tectum':('','Mittelhirndach','n','Tectum mesencephali','tecti mesencephali'),
 'metencephalon':('','Hinterhirn','n','Metencephalon','metencephali'),
 'telencephalon':('','Endhirn','n','Telencephalon','telencephali'),
 'diencephalon':('','Zwischenhirn','n','Diencephalon','diencephali'),
 'thalamus':('','Thalamus','m','Thalamus','thalami'),
 'cerebral hemisphere':('','Großhirnhemisphäre','f','Hemispherium cerebri','hemispherii cerebri'),
 'cerebral cortex':('','Großhirnrinde','f','Cortex cerebri','corticis cerebri'),
 'cerebral white matter':('weiß','Substanz des Großhirns','f','Substantia alba cerebri','substantiae albae cerebri'),
 'white matter of neuraxis':('weiß','Substanz der Neuraxis','f','Substantia alba neuraxis','substantiae albae neuraxis'),
 'frontal lobe':('','Stirnlappen','m','Lobus frontalis','lobi frontalis'),
 'gyrus of cerebral hemisphere':('','Großhirnwindung','f','Gyrus hemispherii cerebri','gyri hemispherii cerebri'),
 'superior temporal gyrus':('ober','Schläfenwindung','f','Gyrus temporalis superior','gyri temporalis superioris'),
 'ventricular system of brain':('','Ventrikelsystem des Gehirns','n','Systema ventriculare encephali','systematis ventricularis encephali'),
 'ventricular system of neuraxis':('','Ventrikelsystem der Neuraxis','n','Systema ventriculare neuraxis','systematis ventricularis neuraxis'),
 'wall of ventricular system of neuraxis':('','Wand des Ventrikelsystems der Neuraxis','f','Paries systematis ventricularis neuraxis','parietis systematis ventricularis neuraxis'),
 'cerebral arterial circle':('','Hirnarterienkreis','m','Circulus arteriosus cerebri','circuli arteriosi cerebri'),
 'cerebral part of internal carotid artery':('','Hirnabschnitt der inneren Halsschlagader','m','Pars cerebralis arteriae carotidis internae','partis cerebralis arteriae carotidis internae'),
 # heart / vessels (generic)
 'aorta':('','Aorta','f','Aorta','aortae'),
 'brachial vein':('','Oberarmvene','f','Vena brachialis','venae brachialis'),
 'deep palmar arterial arch':('tief','Hohlhandbogen','m','Arcus palmaris profundus','arcus palmaris profundi'),
 'lateral superior cerebellar artery':('seitlich ober','Kleinhirnarterie','f','Arteria superior cerebelli lateralis','arteriae superioris cerebelli lateralis'),
 'pulmonary vein':('','Lungenvene','f','Vena pulmonalis','venae pulmonalis'),
 'deep femoral artery':('tief','Oberschenkelarterie','f','Arteria profunda femoris','arteriae profundae femoris'),
 'heart':('','Herz','n','Cor','cordis'),
 'side of heart':('','Herzhälfte','f','Latus cordis','lateris cordis'),
 'wall of heart':('','Herzwand','f','Paries cordis','parietis cordis'),
 'atrium':('','Vorhof','m','Atrium','atrii'),
 'ventricle':('','Herzkammer','f','Ventriculus','ventriculi'),
 'ventricle proper':('eigentlich','Herzkammer','f','Ventriculus proprius','ventriculi proprii'),
 'cardiac chamber':('','Herzhöhle','f','Camera cordis','camerae cordis'),
 'cardiac valve':('','Herzklappe','f','Valva cordis','valvae cordis'),
 'aortic valve':('','Aortenklappe','f','Valva aortae','valvae aortae'),
 'pulmonary valve':('','Pulmonalklappe','f','Valva trunci pulmonalis','valvae trunci pulmonalis'),
 'mitral valve':('','Mitralklappe','f','Valva mitralis','valvae mitralis'),
 'tricuspid valve':('','Trikuspidalklappe','f','Valva tricuspidalis','valvae tricuspidalis'),
 'papillary muscle':('','Papillarmuskel','m','Musculus papillaris','musculi papillaris'),
 'papillary muscle of left ventricle':('','Papillarmuskel der linken Herzkammer','m','Musculus papillaris ventriculi sinistri','musculi papillaris ventriculi sinistri'),
 'lateral papillary muscle of left ventricle':('seitlich','Papillarmuskel der linken Herzkammer','m','Musculus papillaris lateralis ventriculi sinistri','musculi papillaris lateralis ventriculi sinistri'),
 'artery':('','Arterie','f','Arteria','arteriae'),
 'arteries':('','Arterien','p','Arteriae','arteriarum'),
 'systemic artery':('','Körperkreislaufarterie','f','Arteria systemica','arteriae systemicae'),
 'vein':('','Vene','f','Vena','venae'),
 'veins':('','Venen','p','Venae','venarum'),
 'systemic vein':('','Körperkreislaufvene','f','Vena systemica','venae systemicae'),
 'arterial trunk':('','Arterienstamm','m','Truncus arteriosus','trunci arteriosi'),
 'arterial anastomosis':('','Arterienanastomose','f','Anastomosis arteriosa','anastomosis arteriosae'),
 'venous anastomosis':('','Venenanastomose','f','Anastomosis venosa','anastomosis venosae'),
 'arterial tree organ':('','Arterienbaum','m','Arbor arteriosa','arboris arteriosae'),
 'venous tree organ':('','Venenbaum','m','Arbor venosa','arboris venosae'),
 'vascular tree organ':('','Gefäßbaum','m','Arbor vascularis','arboris vascularis'),
 'inferior vena caval tree':('unter','Hohlvenenbaum','m','Arbor venae cavae inferioris','arboris venae cavae inferioris'),
 'superior vena caval tree':('ober','Hohlvenenbaum','m','Arbor venae cavae superioris','arboris venae cavae superioris'),
 'intrapulmonary vein':('intrapulmonal','Vene','f','Vena intrapulmonalis','venae intrapulmonalis'),
 'segmental pulmonary vein':('segmental','Lungenvene','f','Vena pulmonalis segmentalis','venae pulmonalis segmentalis'),
 'external iliac artery proper':('eigentlich äußer','Beckenarterie','f','Arteria iliaca externa propria','arteriae iliacae externae propriae'),
 'coeliac artery':('','Eingeweidearterie','f','Arteria coeliaca','arteriae coeliacae'),
 'costocervical artery':('','Rippen-Hals-Stamm','m','Truncus costocervicalis','trunci costocervicalis'),
 'thyrocervical artery':('','Schilddrüsen-Hals-Stamm','m','Truncus thyrocervicalis','trunci thyrocervicalis'),
 'internal pudendal artery':('inner','Schamarterie','f','Arteria pudenda interna','arteriae pudendae internae'),
 'superficial external pudendal vein':('oberflächlich äußer','Schamvene','f','Vena pudenda externa superficialis','venae pudendae externae superficialis'),
 'external jugular vein':('äußer','Drosselvene','f','Vena jugularis externa','venae jugularis externae'),
 'anterior division of internal iliac artery':('vorder','Ast der inneren Beckenarterie','m','Ramus anterior arteriae iliacae internae','rami anterioris arteriae iliacae internae'),
 'posterior choroidal artery':('hinter','Aderhautarterie','f','Arteria choroidea posterior','arteriae choroideae posterioris'),
 'middle cerebral artery to angular gyrus':('','Ast der mittleren Hirnarterie zum Gyrus angularis','m','Ramus arteriae cerebri mediae ad gyrum angularem','rami arteriae cerebri mediae ad gyrum angularem'),
 'lobe branch of left hepatic artery':('','Lappenast der linken Leberarterie','m','Ramus lobaris arteriae hepaticae sinistrae','rami lobaris arteriae hepaticae sinistrae'),
 'lobe branch of right hepatic artery':('','Lappenast der rechten Leberarterie','m','Ramus lobaris arteriae hepaticae dextrae','rami lobaris arteriae hepaticae dextrae'),
 'subdivision of axillary artery':('','Unterabschnitt der Achselarterie','m','Subdivisio arteriae axillaris','subdivisionis arteriae axillaris'),
 'subdivision of trunk':('','Rumpfabschnitt','m','Subdivisio trunci','subdivisionis trunci'),
 'subdivision of upper limb':('','Abschnitt der oberen Gliedmaße','m','Subdivisio membri superioris','subdivisionis membri superioris'),
 'subdivision of free upper limb':('','Abschnitt der freien oberen Gliedmaße','m','Subdivisio partis liberae membri superioris','subdivisionis partis liberae membri superioris'),
 # thorax / lung
 'lung':('','Lunge','f','Pulmo','pulmonis'),
 'bronchial tree':('','Bronchialbaum','m','Arbor bronchialis','arboris bronchialis'),
 'tracheobronchial tree':('','Tracheobronchialbaum','m','Arbor tracheobronchialis','arboris tracheobronchialis'),
 # abdomen
 'liver':('','Leber','f','Hepar','hepatis'),
 'liver (in-vivo)':('','Leber (in vivo)','f','Hepar (in vivo)','hepatis (in vivo)'),
 'biliary tree':('','Gallengangsystem','n','Arbor biliaris','arboris biliaris'),
 'hepatic biliary tree':('','Gallengangsystem der Leber','n','Arbor biliaris hepatis','arboris biliaris hepatis'),
 'small intestine':('','Dünndarm','m','Intestinum tenue','intestini tenuis'),
 'large intestine':('','Dickdarm','m','Intestinum crassum','intestini crassi'),
 'jejunum':('','Leerdarm','m','Jejunum','jejuni'),
 'ileum':('','Krummdarm','m','Ileum','ilei'),
 'distal part of ileum':('distal','Teil des Krummdarms','m','Pars distalis ilei','partis distalis ilei'),
 'colon':('','Grimmdarm','m','Colon','coli'),
 # muscles as bases
 'adductor hallucis':('','Großzehenanzieher','m','Musculus adductor hallucis','musculi adductoris hallucis'),
 'biceps femoris':('zweiköpfig','Schenkelmuskel','m','Musculus biceps femoris','musculi bicipitis femoris'),
 'flexor hallucis brevis':('kurz','Großzehenbeuger','m','Musculus flexor hallucis brevis','musculi flexoris hallucis brevis'),
 'gastrocnemius':('','Zwillingswadenmuskel','m','Musculus gastrocnemius','musculi gastrocnemii'),
 'cricothyroid':('','Ringknorpel-Schildknorpel-Muskel','m','Musculus cricothyroideus','musculi cricothyroidei'),
 'deltoid':('','Deltamuskel','m','Musculus deltoideus','musculi deltoidei'),
 'levator ani':('','Afterheber','m','Musculus levator ani','musculi levatoris ani'),
 'longus colli':('lang','Halsmuskel','m','Musculus longus colli','musculi longi colli'),
 'oblique arytenoid':('schräg','Stellknorpelmuskel','m','Musculus arytenoideus obliquus','musculi arytenoidei obliqui'),
 'pectoralis major':('groß','Brustmuskel','m','Musculus pectoralis major','musculi pectoralis majoris'),
 'quadriceps femoris':('vierköpfig','Schenkelmuskel','m','Musculus quadriceps femoris','musculi quadricipitis femoris'),
 'trapezius':('','Trapezmuskel','m','Musculus trapezius','musculi trapezii'),
}
NOUN_GEN = {'Bauch':'Bauches','Kopf':'Kopfes','Hals':'Halses','Rumpf':'Rumpfes','Fuß':'Fußes','Knie':'Knies','Mund':'Mundes',
            'Gesicht':'Gesichts','Becken':'Beckens','Gehirn':'Gehirns','Herz':'Herzens','Os':'Os','Damm':'Dammes','Thalamus':'Thalamus',
            'Auge':'Auges','Organ':'Organs','Epithel':'Epithels','Bauchfell':'Bauchfells','Brustbein':'Brustbeins','Skelett':'Skeletts',
            'Ventrikelsystem des Gehirns':'Ventrikelsystems des Gehirns','Ventrikelsystem der Neuraxis':'Ventrikelsystems der Neuraxis'}
