V = {
 'accessory hemiazygos vein':('akzessorisch','Hemiazygosvene','f','Vena hemiazygos accessoria'),
 'hemiazygos vein':('','Hemiazygosvene','f','Vena hemiazygos'),
 'azygos vein':('','Azygosvene','f','Vena azygos'),
 'anterior basal segmental vein':('vorder basal','Segmentvene','f','Vena segmentalis basalis anterior'),
 'posterior basal segmental vein':('hinter basal','Segmentvene','f','Vena segmentalis basalis posterior'),
 'lateral basal segmental vein':('seitlich basal','Segmentvene','f','Vena segmentalis basalis lateralis'),
 'medial basal segmental vein':('medial basal','Segmentvene','f','Vena segmentalis basalis medialis'),
 'anterior segmental vein':('vorder','Segmentvene','f','Vena segmentalis anterior'),
 'posterior segmental vein':('hinter','Segmentvene','f','Vena segmentalis posterior'),
 'apical segmental vein':('apikal','Segmentvene','f','Vena segmentalis apicalis'),
 'superior segmental vein':('ober','Segmentvene','f','Vena segmentalis superior'),
 'lateral segmental vein':('seitlich','Segmentvene','f','Vena segmentalis lateralis'),
 'medial segmental vein':('medial','Segmentvene','f','Vena segmentalis medialis'),
 'superior lingular vein':('ober','Lingula-Vene','f','Vena lingularis superior'),
 'inferior lingular vein':('unter','Lingula-Vene','f','Vena lingularis inferior'),
 'anterior cardiac vein':('vorder','Herzvene','f','Vena cardiaca anterior'),
 'great cardiac vein':('groß','Herzvene','f','Vena cardiaca magna'),
 'middle cardiac vein':('mittler','Herzvene','f','Vena cardiaca media'),
 'small cardiac vein':('klein','Herzvene','f','Vena cardiaca parva'),
 'anterior interventricular vein':('vorder','Zwischenkammervene','f','Vena interventricularis anterior'),
 'coronary sinus':('','Koronarsinus','m','Sinus coronarius'),
 'anterior circumflex humeral vein':('vorder','Oberarm-Zirkumflexvene','f','Vena circumflexa humeri anterior'),
 'circumflex scapular vein':('','Schulterblatt-Zirkumflexvene','f','Vena circumflexa scapulae'),
 'lateral circumflex femoral vein':('seitlich','Oberschenkel-Zirkumflexvene','f','Vena circumflexa femoris lateralis'),
 'medial circumflex femoral vein':('medial','Oberschenkel-Zirkumflexvene','f','Vena circumflexa femoris medialis'),
 'anterior tibial vein':('vorder','Schienbeinvene','f','Vena tibialis anterior'),
 'posterior tibial vein':('hinter','Schienbeinvene','f','Vena tibialis posterior'),
 'fibular vein':('','Wadenbeinvene','f','Vena fibularis'),
 'popliteal vein':('','Kniekehlenvene','f','Vena poplitea'),
 'genicular vein':('','Knievene','f','Vena genicularis'),
 'femoral vein':('','Oberschenkelvene','f','Vena femoralis'),
 'deep femoral vein':('tief','Oberschenkelvene','f','Vena profunda femoris'),
 'great saphenous vein':('groß','Rosenvene','f','Vena saphena magna'),
 'small saphenous vein':('klein','Rosenvene','f','Vena saphena parva'),
 'ascending lumbar vein':('aufsteigend','Lendenvene','f','Vena lumbalis ascendens'),
 'lumbar vein':('','Lendenvene','f','Vena lumbalis'),
 'axillary vein':('','Achselvene','f','Vena axillaris'),
 'basilic vein':('','Basilikavene','f','Vena basilica'),
 'cephalic vein':('','Kopfvene','f','Vena cephalica'),
 'medial brachial vein':('medial','Oberarmvene','f','Vena brachialis medialis'),
 'median antebrachial vein':('mittler','Unterarmvene','f','Vena mediana antebrachii'),
 'median cubital vein':('mittler','Ellenbeugenvene','f','Vena mediana cubiti'),
 'radial vein':('','Speichenvene','f','Vena radialis'),
 'ulnar vein':('','Ellenvene','f','Vena ulnaris'),
 'brachiocephalic vein':('','Arm-Kopf-Vene','f','Vena brachiocephalica'),
 'subclavian vein':('','Unterschlüsselbeinvene','f','Vena subclavia'),
 'internal jugular vein':('inner','Drosselvene','f','Vena jugularis interna'),
 'subscapular vein':('','Unterschulterblattvene','f','Vena subscapularis'),
 'suprascapular vein':('','Oberschulterblattvene','f','Vena suprascapularis'),
 'thoracodorsal vein':('','Brust-Rücken-Vene','f','Vena thoracodorsalis'),
 'internal thoracic vein':('inner','Brustwandvene','f','Vena thoracica interna'),
 'lateral thoracic vein':('seitlich','Brustwandvene','f','Vena thoracica lateralis'),
 'superior intercostal vein':('ober','Zwischenrippenvene','f','Vena intercostalis superior'),
 'subcostal vein':('','Unterrippenvene','f','Vena subcostalis'),
 'musculophrenic vein':('','Muskel-Zwerchfell-Vene','f','Vena musculophrenica'),
 'superior phrenic vein':('ober','Zwerchfellvene','f','Vena phrenica superior'),
 'inferior phrenic vein':('unter','Zwerchfellvene','f','Vena phrenica inferior'),
 'superior pulmonary vein':('ober','Lungenvene','f','Vena pulmonalis superior'),
 'inferior pulmonary vein':('unter','Lungenvene','f','Vena pulmonalis inferior'),
 'superior vena cava':('ober','Hohlvene','f','Vena cava superior'),
 'inferior vena cava':('unter','Hohlvene','f','Vena cava inferior'),
 'superior epigastric vein':('ober','Bauchdeckenvene','f','Vena epigastrica superior'),
 'inferior epigastric vein':('unter','Bauchdeckenvene','f','Vena epigastrica inferior'),
 'superficial epigastric vein':('oberflächlich','Bauchdeckenvene','f','Vena epigastrica superficialis'),
 'colic vein':('','Dickdarmvene','f','Vena colica'),
 'middle colic vein':('mittler','Dickdarmvene','f','Vena colica media'),
 'sigmoid vein':('','Sigmavene','f','Vena sigmoidea'),
 'superior rectal vein':('ober','Mastdarmvene','f','Vena rectalis superior'),
 'ileal vein':('','Krummdarmvene','f','Vena ilealis'),
 'ileocolic vein':('','Ileokolikvene','f','Vena ileocolica'),
 'superior mesenteric vein':('ober','Gekrösevene','f','Vena mesenterica superior'),
 'inferior mesenteric vein':('unter','Gekrösevene','f','Vena mesenterica inferior'),
 'gastric vein':('','Magenvene','f','Vena gastrica'),
 'gastroepiploic vein':('','Magen-Netz-Vene','f','Vena gastroomentalis'),
 'pancreaticoduodenal vein':('','Pankreas-Duodenal-Vene','f','Vena pancreaticoduodenalis'),
 'splenic vein':('','Milzvene','f','Vena splenica'),
 'portal vein':('','Pfortader','f','Vena portae'),
 'hepatic portal vein':('','Pfortader','f','Vena portae hepatis'),
 'pre-hepatic portal vein':('prähepatisch','Pfortader','f','Vena portae prehepatica'),
 'hepatic vein':('','Lebervene','f','Vena hepatica'),
 'middle hepatic vein':('mittler','Lebervene','f','Vena hepatica intermedia'),
 'renal vein':('','Nierenvene','f','Vena renalis'),
 'suprarenal vein':('','Nebennierenvene','f','Vena suprarenalis'),
 'testicular vein':('','Hodenvene','f','Vena testicularis'),
 'common iliac vein':('gemeinsam','Beckenvene','f','Vena iliaca communis'),
 'external iliac vein':('äußer','Beckenvene','f','Vena iliaca externa'),
 'internal iliac vein':('inner','Beckenvene','f','Vena iliaca interna'),
 'iliolumbar vein':('','Darmbein-Lenden-Vene','f','Vena iliolumbalis'),
 'lateral sacral vein':('seitlich','Kreuzbeinvene','f','Vena sacralis lateralis'),
 'median sacral vein':('mittler','Kreuzbeinvene','f','Vena sacralis mediana'),
 'superior gluteal vein':('ober','Gesäßvene','f','Vena glutea superior'),
 'inferior gluteal vein':('unter','Gesäßvene','f','Vena glutea inferior'),
 'obturator vein':('','Hüftlochvene','f','Vena obturatoria'),
 'internal pudendal vein':('inner','Schamvene','f','Vena pudenda interna'),
 'deep dorsal vein of penis':('tief dorsal','Penisvene','f','Vena dorsalis profunda penis'),
 'superficial dorsal vein of penis':('oberflächlich dorsal','Penisvene','f','Vena dorsalis superficialis penis'),
 'deep palmar venous arch':('tief','Hohlhand-Venenbogen','m','Arcus venosus palmaris profundus'),
 'superficial palmar venous arch':('oberflächlich','Hohlhand-Venenbogen','m','Arcus venosus palmaris superficialis'),
 'common palmar digital vein':('gemeinsam','Hohlhand-Fingervene','f','Vena digitalis palmaris communis'),
 'palmar metacarpal vein':('','Hohlhand-Mittelhandvene','f','Vena metacarpalis palmaris'),
 'dorsal metacarpal vein':('dorsal','Mittelhandvene','f','Vena metacarpalis dorsalis'),
 'dorsal venous network of hand':('dorsal','Handvenennetz','n','Rete venosum dorsale manus'),
 'dorsal venous arch of foot':('dorsal','Fußvenenbogen','m','Arcus venosus dorsalis pedis'),
 'plantar venous arch of foot':('','Fußsohlen-Venenbogen','m','Arcus venosus plantaris pedis'),
 'plantar venous arch':('','Fußsohlen-Venenbogen','m','Arcus venosus plantaris'),
 'plantar metatarsal vein':('','Fußsohlen-Mittelfußvene','f','Vena metatarsalis plantaris'),
 'marginal vein':('','Randvene','f','Vena marginalis'),
}
VBR = {
 'anterior inferior segmental':('vorder unter','Segment','segmentalis anterior inferior'),
 'anterior superior segmental':('vorder ober','Segment','segmentalis anterior superior'),
 'lateral inferior segmental':('seitlich unter','Segment','segmentalis lateralis inferior'),
 'lateral superior segmental':('seitlich ober','Segment','segmentalis lateralis superior'),
 'medial inferior segmental':('medial unter','Segment','segmentalis medialis inferior'),
 'medial superior segmental':('medial ober','Segment','segmentalis medialis superior'),
 'posterior inferior segmental':('hinter unter','Segment','segmentalis posterior inferior'),
 'posterior superior segmental':('hinter ober','Segment','segmentalis posterior superior'),
}
VPARTS = {'inferior':('unter','inferior'), 'superior':('ober','superior')}
VFIXED = {
 'set of anterior intercostal veins':('Vordere Zwischenrippenvenen','Venae intercostales anteriores'),
 'set of dorsal digital veins':('Rückseitige Fingervenen','Venae digitales dorsales'),
 'set of perforating veins':('Perforansvenen','Venae perforantes'),
 'set of plantar digital veins':('Fußsohlen-Zehenvenen','Venae digitales plantares'),
 'posterior vein of left ventricle':('Hintere Vene der linken Herzkammer','Vena posterior ventriculi sinistri'),
 'posterior vein of right ventricle':('Hintere Vene der rechten Herzkammer','Vena posterior ventriculi dextri'),
}
ROMAN = {'ii':'II','iii':'III','iv':'IV','v':'V','vi':'VI','vii':'VII','viii':'VIII','ix':'IX'}
for r,R in ROMAN.items():
    VFIXED[f'hepatovenous segment {r}'] = (f'Lebervenensegment {R}', f'Segmentum hepatovenosum {R}')
