# New in 4.3: base entries for the vessel engine -> (german adj stems, german noun, gender, latin)
A43 = {
 # --- cranial and peripheral nerves ---
 'abducens nerve':('','Augenabziehernerv','m','Nervus abducens'),
 'accessory nerve':('','Beinerv','m','Nervus accessorius'),
 'facial nerve':('','Gesichtsnerv','m','Nervus facialis'),
 'glossopharyngeal nerve':('','Zungen-Rachen-Nerv','m','Nervus glossopharyngeus'),
 'hypoglossal nerve':('','Unterzungennerv','m','Nervus hypoglossus'),
 'vagus nerve':('','Vagusnerv','m','Nervus vagus'),
 'trigeminal nerve':('','Drillingsnerv','m','Nervus trigeminus'),
 'mandibular nerve':('','Unterkiefernerv','m','Nervus mandibularis'),
 'maxillary nerve':('','Oberkiefernerv','m','Nervus maxillaris'),
 'lingual nerve':('','Zungennerv','m','Nervus lingualis'),
 'buccal nerve':('','Wangennerv','m','Nervus buccalis'),
 'masseteric nerve':('','Kaumuskelnerv','m','Nervus massetericus'),
 'auriculotemporal nerve':('','Ohr-Schläfen-Nerv','m','Nervus auriculotemporalis'),
 'inferior alveolar nerve':('unter','Zahnfachnerv','m','Nervus alveolaris inferior'),
 'anterior superior alveolar nerve':('vorder ober','Zahnfachnerv','m','Nervus alveolaris superior anterior'),
 'posterior superior alveolar nerve':('hinter ober','Zahnfachnerv','m','Nervus alveolaris superior posterior'),
 'greater palatine nerve':('groß','Gaumennerv','m','Nervus palatinus major'),
 'lesser palatine nerve':('klein','Gaumennerv','m','Nervus palatinus minor'),
 'external nasal nerve':('äußer','Nasennerv','m','Nervus nasalis externus'),
 'lateral posterior superior nasal nerve':('seitlich hinter ober','Nasennerv','m','Nervus nasalis posterior superior lateralis'),
 'medial posterior superior nasal nerve':('medial hinter ober','Nasennerv','m','Nervus nasalis posterior superior medialis'),
 'lateral pterygoid nerve':('seitlich','Flügelmuskelnerv','m','Nervus pterygoideus lateralis'),
 'medial pterygoid nerve':('medial','Flügelmuskelnerv','m','Nervus pterygoideus medialis'),
 'great auricular nerve':('groß','Ohrnerv','m','Nervus auricularis magnus'),
 'lesser occipital nerve':('klein','Hinterhauptnerv','m','Nervus occipitalis minor'),
 'greater occipital nerve':('groß','Hinterhauptnerv','m','Nervus occipitalis major'),
 'axillary nerve':('','Achselnerv','m','Nervus axillaris'),
 'musculocutaneous nerve':('','Muskel-Haut-Nerv','m','Nervus musculocutaneus'),
 'median nerve':('','Mittelnerv','m','Nervus medianus'),
 'ulnar nerve':('','Ellennerv','m','Nervus ulnaris'),
 'radial nerve':('','Speichennerv','m','Nervus radialis'),
 'anterior interosseous nerve':('vorder','Zwischenknochennerv','m','Nervus interosseus anterior'),
 'posterior interosseous nerve':('hinter','Zwischenknochennerv','m','Nervus interosseus posterior'),
 'long thoracic nerve':('lang','Brustkorbnerv','m','Nervus thoracicus longus'),
 'phrenic nerve':('','Zwerchfellnerv','m','Nervus phrenicus'),
 'intercostal nerve':('','Zwischenrippennerv','m','Nervus intercostalis'),
 'first intercostal nerve':('erst','Zwischenrippennerv','m','Nervus intercostalis primus'),
 'second intercostal nerve':('zweit','Zwischenrippennerv','m','Nervus intercostalis secundus'),
 'brachial nerve plexus':('','Armnervengeflecht','n','Plexus brachialis'),
 'ansa cervicalis':('','Halsschlinge','f','Ansa cervicalis'),
 'cauda equina':('','Pferdeschweif','m','Cauda equina'),
 'otic ganglion':('','Ohrganglion','n','Ganglion oticum'),
 'pterygopalatine ganglion':('','Flügelgaumenganglion','n','Ganglion pterygopalatinum'),
 'submandibular ganglion':('','Unterkieferganglion','n','Ganglion submandibulare'),
 'trigeminal ganglion':('','Drillingsnervknoten','m','Ganglion trigeminale'),
 'first cervical nerve':('erst','Halsnerv','m','Nervus cervicalis primus'),
 'second cervical nerve':('zweit','Halsnerv','m','Nervus cervicalis secundus'),
 'third cervical nerve':('dritt','Halsnerv','m','Nervus cervicalis tertius'),
 'fourth cervical nerve':('viert','Halsnerv','m','Nervus cervicalis quartus'),
 'fifth cervical nerve':('fünft','Halsnerv','m','Nervus cervicalis quintus'),
 'sixth cervical nerve':('sechst','Halsnerv','m','Nervus cervicalis sextus'),
 'seventh cervical nerve':('siebt','Halsnerv','m','Nervus cervicalis septimus'),
 'eighth cervical nerve':('acht','Halsnerv','m','Nervus cervicalis octavus'),
 'first thoracic nerve':('erst','Brustnerv','m','Nervus thoracicus primus'),
 # --- head and neck arteries ---
 'external carotid artery':('äußer','Halsschlagader','f','Arteria carotis externa'),
 'facial artery':('','Gesichtsarterie','f','Arteria facialis'),
 'lingual artery':('','Zungenarterie','f','Arteria lingualis'),
 'maxillary artery':('','Oberkieferarterie','f','Arteria maxillaris'),
 'superficial temporal artery':('oberflächlich','Schläfenarterie','f','Arteria temporalis superficialis'),
 'middle meningeal artery':('mittler','Hirnhautarterie','f','Arteria meningea media'),
 'ascending pharyngeal artery':('aufsteigend','Rachenarterie','f','Arteria pharyngea ascendens'),
 'ascending cervical artery':('aufsteigend','Halsarterie','f','Arteria cervicalis ascendens'),
 'occipital artery':('','Hinterhauptarterie','f','Arteria occipitalis'),
 'posterior auricular artery':('hinter','Ohrarterie','f','Arteria auricularis posterior'),
 'deep auricular artery':('tief','Ohrarterie','f','Arteria auricularis profunda'),
 'superior thyroid artery':('ober','Schilddrüsenarterie','f','Arteria thyroidea superior'),
 'infrahyoid artery':('','Unterzungenbeinarterie','f','Arteria infrahyoidea'),
 'cricothyroid artery':('','Ringknorpel-Schildknorpel-Arterie','f','Arteria cricothyroidea'),
 'inferior alveolar artery':('unter','Zahnfacharterie','f','Arteria alveolaris inferior'),
 'posterior superior alveolar artery':('hinter ober','Zahnfacharterie','f','Arteria alveolaris superior posterior'),
 'buccal artery':('','Wangenarterie','f','Arteria buccalis'),
 'masseteric artery':('','Kaumuskelarterie','f','Arteria masseterica'),
 'anterior deep temporal artery':('vorder tief','Schläfenarterie','f','Arteria temporalis profunda anterior'),
 'posterior deep temporal artery':('hinter tief','Schläfenarterie','f','Arteria temporalis profunda posterior'),
 'anterior tympanic artery':('vorder','Paukenhöhlenarterie','f','Arteria tympanica anterior'),
 'inferior tympanic artery':('unter','Paukenhöhlenarterie','f','Arteria tympanica inferior'),
 'descending palatine artery':('absteigend','Gaumenarterie','f','Arteria palatina descendens'),
 'greater palatine artery':('groß','Gaumenarterie','f','Arteria palatina major'),
 'lesser palatine artery':('klein','Gaumenarterie','f','Arteria palatina minor'),
 'sphenopalatine artery':('','Keilbein-Gaumen-Arterie','f','Arteria sphenopalatina'),
 'infra-orbital artery':('','Unteraugenhöhlenarterie','f','Arteria infraorbitalis'),
 'angular artery':('','Winkelarterie','f','Arteria angularis'),
 'lateral nasal artery':('seitlich','Nasenarterie','f','Arteria nasalis lateralis'),
 'dorsal nasal artery':('dorsal','Nasenarterie','f','Arteria dorsalis nasi'),
 'superior labial artery':('ober','Lippenarterie','f','Arteria labialis superior'),
 'inferior labial artery':('unter','Lippenarterie','f','Arteria labialis inferior'),
 'lacrimal artery':('','Tränendrüsenarterie','f','Arteria lacrimalis'),
 'lateral palpebral artery':('seitlich','Lidarterie','f','Arteria palpebralis lateralis'),
 'medial palpebral artery':('medial','Lidarterie','f','Arteria palpebralis medialis'),
 'central retinal artery':('zentral','Netzhautarterie','f','Arteria centralis retinae'),
 'long posterior ciliary artery':('lang hinter','Ziliararterie','f','Arteria ciliaris posterior longa'),
 'short posterior ciliary artery':('kurz hinter','Ziliararterie','f','Arteria ciliaris posterior brevis'),
 'supra-orbital artery':('','Oberaugenhöhlenarterie','f','Arteria supraorbitalis'),
 'supratrochlear artery':('','Supratrochleararterie','f','Arteria supratrochlearis'),
 'anterior ethmoidal artery':('vorder','Siebbeinarterie','f','Arteria ethmoidalis anterior'),
 'posterior ethmoidal artery':('hinter','Siebbeinarterie','f','Arteria ethmoidalis posterior'),
 'inferior hypophyseal artery':('unter','Hypophysenarterie','f','Arteria hypophysialis inferior'),
 'superior hypophyseal artery':('ober','Hypophysenarterie','f','Arteria hypophysialis superior'),
 'collicular artery':('','Hügelarterie','f','Arteria collicularis'),
 'calcarine artery':('','Calcarina-Arterie','f','Arteria calcarina'),
 'mammillary artery':('','Corpus-mamillare-Arterie','f','Arteria corporis mamillaris'),
 'distal medial striate artery':('distal medial','Striatumarterie','f','Arteria striata medialis distalis'),
 'carotid sinus':('','Karotissinus','m','Sinus caroticus'),
 'bronchial artery':('','Bronchialarterie','f','Arteria bronchialis'),
 # --- head and neck veins, dural sinuses ---
 'external jugular vein':('äußer','Drosselvene','f','Vena jugularis externa'),
 'anterior jugular vein':('vorder','Drosselvene','f','Vena jugularis anterior'),
 'facial vein':('','Gesichtsvene','f','Vena facialis'),
 'maxillary vein':('','Oberkiefervene','f','Vena maxillaris'),
 'retromandibular vein':('','Retromandibularvene','f','Vena retromandibularis'),
 'lingual vein':('','Zungenvene','f','Vena lingualis'),
 'deep lingual vein':('tief','Zungenvene','f','Vena profunda linguae'),
 'superior thyroid vein':('ober','Schilddrüsenvene','f','Vena thyroidea superior'),
 'inferior thyroid vein':('unter','Schilddrüsenvene','f','Vena thyroidea inferior'),
 'deep cervical vein':('tief','Halsvene','f','Vena cervicalis profunda'),
 'anterior vertebral vein':('vorder','Wirbelvene','f','Vena vertebralis anterior'),
 'angular vein':('','Winkelvene','f','Vena angularis'),
 'external nasal vein':('äußer','Nasenvene','f','Vena nasalis externa'),
 'superior labial vein':('ober','Lippenvene','f','Vena labialis superior'),
 'inferior labial vein':('unter','Lippenvene','f','Vena labialis inferior'),
 'lacrimal vein':('','Tränendrüsenvene','f','Vena lacrimalis'),
 'central retinal vein':('zentral','Netzhautvene','f','Vena centralis retinae'),
 'superior ophthalmic vein':('ober','Augenvene','f','Vena ophthalmica superior'),
 'inferior ophthalmic vein':('unter','Augenvene','f','Vena ophthalmica inferior'),
 'mastoid emissary vein':('','Warzenfortsatz-Emissarvene','f','Vena emissaria mastoidea'),
 'jugular venous arch':('','Drosselvenenbogen','m','Arcus venosus jugularis'),
 'superior sagittal sinus':('ober','Sichelblutleiter','m','Sinus sagittalis superior'),
 'inferior sagittal sinus':('unter','Sichelblutleiter','m','Sinus sagittalis inferior'),
 'straight sinus':('','Gerader Blutleiter','m','Sinus rectus'),
 'transverse sinus':('','Querer Blutleiter','m','Sinus transversus'),
 'sigmoid sinus':('','S-förmiger Blutleiter','m','Sinus sigmoideus'),
 'cavernous sinus':('','Kavernöser Sinus','m','Sinus cavernosus'),
 'superior petrosal sinus':('ober','Felsenbeinsinus','m','Sinus petrosus superior'),
 'inferior petrosal sinus':('unter','Felsenbeinsinus','m','Sinus petrosus inferior'),
 'occipital sinus':('','Hinterhauptsinus','m','Sinus occipitalis'),
 'marginal sinus':('','Randsinus','m','Sinus marginalis'),
 'anterior intercavernous sinus':('vorder','Interkavernöser Sinus','m','Sinus intercavernosus anterior'),
 'posterior intercavernous sinus':('hinter','Interkavernöser Sinus','m','Sinus intercavernosus posterior'),
 'basilar venous plexus':('','Basilarvenengeflecht','n','Plexus basilaris'),
 'confluence of sinuses':('','Sinuszusammenfluss','m','Confluens sinuum'),
 'great cerebral vein':('groß','Hirnvene','f','Vena magna cerebri'),
 'internal cerebral vein':('inner','Hirnvene','f','Vena interna cerebri'),
 'superior cerebral vein':('ober','Hirnvene','f','Vena superior cerebri'),
 'inferior cerebral vein':('unter','Hirnvene','f','Vena inferior cerebri'),
 'anterior cerebral vein':('vorder','Hirnvene','f','Vena anterior cerebri'),
 'deep middle cerebral vein':('tief mittler','Hirnvene','f','Vena media profunda cerebri'),
 'superior anastomotic vein':('ober','Anastomosenvene','f','Vena anastomotica superior'),
 'inferior anastomotic vein':('unter','Anastomosenvene','f','Vena anastomotica inferior'),
 'basal vein':('','Basalvene','f','Vena basalis'),
 'superior thalamostriate vein':('ober','Thalamostriatvene','f','Vena thalamostriata superior'),
 'inferior choroid vein':('unter','Adergeflechtvene','f','Vena choroidea inferior'),
 'superior choroid vein':('ober','Adergeflechtvene','f','Vena choroidea superior'),
 'interpeduncular vein':('','Interpedunkularvene','f','Vena interpeduncularis'),
 'inferior vein of vermis':('unter','Wurmvene','f','Vena inferior vermis'),
 'superior vein of vermis':('ober','Wurmvene','f','Vena superior vermis'),
 'anterolateral medullary vein':('anterolateral','Medullavene','f','Vena medullaris anterolateralis'),
 'anteromedian medullary vein':('anteromedian','Medullavene','f','Vena medullaris anteromediana'),
 'dorsal medullary vein':('dorsal','Medullavene','f','Vena medullaris dorsalis'),
 'anterolateral pontine vein':('anterolateral','Brückenvene','f','Vena pontis anterolateralis'),
 'anteromedian pontine vein':('anteromedian','Brückenvene','f','Vena pontis anteromediana'),
 # --- brain / hypothalamus ---
 'cerebral crus':('','Hirnschenkelfuß','m','Crus cerebri'),
 'cuneus':('','Cuneus','m','Cuneus'),
 'precuneus':('','Precuneus','m','Precuneus'),
 'lingual gyrus':('','Lingualwindung','f','Gyrus lingualis'),
 'lateral occipital gyrus':('seitlich','Hinterhauptwindung','f','Gyrus occipitalis lateralis'),
 'anterior orbital gyrus':('vorder','Orbitalwindung','f','Gyrus orbitalis anterior'),
 'lateral orbital gyrus':('seitlich','Orbitalwindung','f','Gyrus orbitalis lateralis'),
 'medial orbital gyrus':('medial','Orbitalwindung','f','Gyrus orbitalis medialis'),
 'posterior orbital gyrus':('hinter','Orbitalwindung','f','Gyrus orbitalis posterior'),
 'hippocampus proper':('eigentlich','Hippocampus','m','Hippocampus proprius'),
 'anterior nucleus of hypothalamus':('vorder','Hypothalamuskern','m','Nucleus anterior hypothalami'),
 'arcuate nucleus of hypothalamus':('','Bogenkern des Hypothalamus','m','Nucleus arcuatus hypothalami'),
 'dorsomedial nucleus of hypothalamus':('dorsomedial','Hypothalamuskern','m','Nucleus dorsomedialis hypothalami'),
 'ventromedial nucleus of hypothalamus':('ventromedial','Hypothalamuskern','m','Nucleus ventromedialis hypothalami'),
 'posterior nucleus of hypothalamus':('hinter','Hypothalamuskern','m','Nucleus posterior hypothalami'),
 'lateral hypothalamic nucleus':('seitlich','Hypothalamuskern','m','Nucleus hypothalamicus lateralis'),
 'lateral preoptic nucleus':('seitlich','Präoptikkern','m','Nucleus preopticus lateralis'),
 'medial preoptic nucleus':('medial','Präoptikkern','m','Nucleus preopticus medialis'),
 'supraoptic nucleus':('','Supraoptikkern','m','Nucleus supraopticus'),
 'paraventricular nucleus':('','Paraventrikularkern','m','Nucleus paraventricularis'),
 'mammillothalamic tract of hypothalamus':('','Mammillothalamischer Trakt','m','Tractus mammillothalamicus'),
 'falx cerebri':('','Hirnsichel','f','Falx cerebri'),
 # --- other ---
 'inferior parathyroid gland':('unter','Nebenschilddrüse','f','Glandula parathyroidea inferior'),
 'superior parathyroid gland':('ober','Nebenschilddrüse','f','Glandula parathyroidea superior'),
 'thyroid gland':('','Schilddrüse','f','Glandula thyroidea'),
 'inguinal ligament':('','Leistenband','n','Ligamentum inguinale'),
 'stylomandibular ligament':('','Griffel-Unterkiefer-Band','n','Ligamentum stylomandibulare'),
 'sphenomandibular ligament':('','Keilbein-Unterkiefer-Band','n','Ligamentum sphenomandibulare'),
 'temporal bone':('','Schläfenbein','n','Os temporale'),
 'mandibular gingiva':('','Zahnfleisch des Unterkiefers','n','Gingiva mandibularis'),
 'maxillary gingiva':('','Zahnfleisch des Oberkiefers','n','Gingiva maxillaris'),
 'tensor tympani':('','Trommelfellspanner','m','Musculus tensor tympani'),
 'infraspinatus':('','Untergrätenmuskel','m','Musculus infraspinatus'),
}
# branch/part modifiers new in 4.3 -> (german adj stems, german noun prefix, latin masc adjective)
BR43 = {
 'buccal':('','Wangen','buccalis'), 'cervical':('','Hals','cervicalis'), 'marginal mandibular':('','Unterkieferrand','marginalis mandibulae'),
 'temporal':('','Schläfen','temporalis'), 'zygomatic':('','Jochbein','zygomaticus'), 'frontal':('','Stirn','frontalis'),
 'parietal':('','Scheitel','parietalis'), 'dental':('','Zahn','dentalis'), 'cavernous':('','Kavernosus','cavernosus'),
 'clivus':('','Clivus','clivalis'), 'chiasmatic':('','Chiasma','chiasmaticus'), 'glandular':('','Drüsen','glandularis'),
 'anterior glandular':('vorder','Drüsen','glandularis anterior'), 'lateral glandular':('seitlich','Drüsen','glandularis lateralis'),
 'posterior glandular':('hinter','Drüsen','glandularis posterior'),
 'anterior cutaneous':('vorder','Haut','cutaneus anterior'), 'lateral cutaneous':('seitlich','Haut','cutaneus lateralis'),
 'external nasal':('äußer','Nasen','nasalis externus'), 'internal nasal':('inner','Nasen','nasalis internus'),
 'lateral internal nasal':('seitlich inner','Nasen','nasalis internus lateralis'),
 'medial internal nasal':('medial inner','Nasen','nasalis internus medialis'),
 'inferior palpebral':('unter','Lid','palpebralis inferior'), 'superior palpebral':('ober','Lid','palpebralis superior'),
 'ganglionic':('','Ganglien','ganglionicus'), 'meningeal':('','Hirnhaut','meningeus'),
 'anteromedial frontal':('anteromedial','Stirn','frontalis anteromedialis'),
 'posteromedial frontal':('posteromedial','Stirn','frontalis posteromedialis'),
 'intermediomedial frontal':('intermediomedial','Stirn','frontalis intermediomedialis'),
 'first dorsal digital':('erst dorsal','Finger','digitalis dorsalis primus'),
 'second dorsal digital':('zweit dorsal','Finger','digitalis dorsalis secundus'),
 'dorsal digital':('dorsal','Finger','digitalis dorsalis'),
 'lateral dorsal digital':('seitlich dorsal','Finger','digitalis dorsalis lateralis'),
 'medial dorsal digital':('medial dorsal','Finger','digitalis dorsalis medialis'),
 'lateral proper palmar digital':('seitlich eigentlich','Hohlhand-Finger','digitalis palmaris proprius lateralis'),
 'medial proper palmar digital':('medial eigentlich','Hohlhand-Finger','digitalis palmaris proprius medialis'),
 'superior root':('ober','Wurzel','radix superior'), 'inferior root':('unter','Wurzel','radix inferior'),
 'superior trunk':('ober','Stamm','truncus superior'), 'middle trunk':('mittler','Stamm','truncus medius'),
 'inferior trunk':('unter','Stamm','truncus inferior'),
 'lateral cord':('seitlich','Faszikel','fasciculus lateralis'), 'medial cord':('medial','Faszikel','fasciculus medialis'),
 'posterior cord':('hinter','Faszikel','fasciculus posterior'),
}
